from datetime import date, timedelta
from itertools import islice

from financial_simulator import generate_states
from financial_simulator.core import Child
from test_utils import LogContainer, LogActor, LogAction, TICK_EVENT, ACTION_EVENT

DAY_0 = date(2021, 1, 1)
DAY_1 = DAY_0 + timedelta(days=1)
DAY_2 = DAY_1 + timedelta(days=1)


def test_container_without_event_mappers() -> None:
    initial_state = LogContainer(current_date=DAY_0,
                                 action_log=(),
                                 children=(Child('one', LogActor(DAY_0, ())),
                                           Child('two', LogActor(DAY_0, ())),
                                           Child('three', LogActor(DAY_0, ()))),
                                 maps=())
    assert tuple(islice(generate_states(initial_state=initial_state),
                        2)) == (
               (LogContainer(current_date=DAY_1,
                             action_log=(),
                             children=(Child('one', LogActor(DAY_1, ())),
                                       Child('two', LogActor(DAY_1, ())),
                                       Child('three', LogActor(DAY_1, ()))),
                             maps=()), ()),
               (LogContainer(current_date=DAY_2,
                             action_log=(),
                             children=(Child('one', LogActor(DAY_2, ())),
                                       Child('two', LogActor(DAY_2, ())),
                                       Child('three', LogActor(DAY_2, ()))),
                             maps=()), ()))


def test_container_with_event_mappers() -> None:
    initial_state = LogContainer(current_date=DAY_0,
                                 action_log=(),
                                 children=(Child('one', LogActor(DAY_0, ())),
                                           Child('two', LogActor(DAY_0, ())),
                                           Child('three', LogActor(DAY_0, ()))),
                                 maps=(('one', 'two'),
                                       ('two', 'three'),
                                       ('three', 'one')))
    assert tuple(islice(generate_states(initial_state=initial_state),
                        2)) == (
               (LogContainer(current_date=DAY_1,
                             action_log=(),
                             children=(Child(name='one',
                                             state=LogActor(current_date=DAY_1,
                                                            action_log=((DAY_1,
                                                                         LogAction(source=('..', 'three'),
                                                                                   destination=(),
                                                                                   name=TICK_EVENT)),
                                                                        (DAY_1,
                                                                         LogAction(source=('..', 'three'),
                                                                                   destination=(),
                                                                                   name=ACTION_EVENT))))),
                                       Child(name='two',
                                             state=LogActor(current_date=DAY_1,
                                                            action_log=((DAY_1,
                                                                         LogAction(source=('..', 'one'),
                                                                                   destination=(),
                                                                                   name=TICK_EVENT)),
                                                                        (DAY_1,
                                                                         LogAction(source=('..', 'one'),
                                                                                   destination=(),
                                                                                   name=ACTION_EVENT))))),
                                       Child(name='three',
                                             state=LogActor(current_date=DAY_1,
                                                            action_log=((DAY_1,
                                                                         LogAction(source=('..', 'two'),
                                                                                   destination=(),
                                                                                   name=TICK_EVENT)),
                                                                        (DAY_1,
                                                                         LogAction(source=('..', 'two'),
                                                                                   destination=(),
                                                                                   name=ACTION_EVENT)))))),
                             maps=(('one', 'two'),
                                   ('two', 'three'),
                                   ('three', 'one'))), ()),
               (LogContainer(current_date=DAY_2,
                             action_log=(),
                             children=(Child(name='one',
                                             state=LogActor(current_date=DAY_2,
                                                            action_log=((DAY_1,
                                                                         LogAction(source=('..', 'three'),
                                                                                   destination=(),
                                                                                   name=TICK_EVENT)),
                                                                        (DAY_1,
                                                                         LogAction(source=('..', 'three'),
                                                                                   destination=(),
                                                                                   name=ACTION_EVENT)),
                                                                        (DAY_2,
                                                                         LogAction(source=('..', 'three'),
                                                                                   destination=(),
                                                                                   name=TICK_EVENT)),
                                                                        (DAY_2,
                                                                         LogAction(source=('..', 'three'),
                                                                                   destination=(),
                                                                                   name=ACTION_EVENT))))),
                                       Child(name='two',
                                             state=LogActor(current_date=DAY_2,
                                                            action_log=((DAY_1,
                                                                         LogAction(source=('..', 'one'),
                                                                                   destination=(),
                                                                                   name=TICK_EVENT)),
                                                                        (DAY_1,
                                                                         LogAction(source=('..', 'one'),
                                                                                   destination=(),
                                                                                   name=ACTION_EVENT)),
                                                                        (DAY_2,
                                                                         LogAction(source=('..', 'one'),
                                                                                   destination=(),
                                                                                   name=TICK_EVENT)),
                                                                        (DAY_2,
                                                                         LogAction(source=('..', 'one'),
                                                                                   destination=(),
                                                                                   name=ACTION_EVENT))))),
                                       Child(name='three',
                                             state=LogActor(current_date=DAY_2,
                                                            action_log=((DAY_1,
                                                                         LogAction(source=('..', 'two'),
                                                                                   destination=(),
                                                                                   name=TICK_EVENT)),
                                                                        (DAY_1,
                                                                         LogAction(source=('..', 'two'),
                                                                                   destination=(),
                                                                                   name=ACTION_EVENT)),
                                                                        (DAY_2,
                                                                         LogAction(source=('..', 'two'),
                                                                                   destination=(),
                                                                                   name=TICK_EVENT)),
                                                                        (DAY_2,
                                                                         LogAction(source=('..', 'two'),
                                                                                   destination=(),
                                                                                   name=ACTION_EVENT)))))),
                             maps=(('one', 'two'),
                                   ('two', 'three'),
                                   ('three', 'one'))), ()))
