from financial_simulator.app.database.schema import BankAccount
from financial_simulator.app.server.util.dependent import create_dependent_get_mapper

bank_account_dependent_get_mapper = create_dependent_get_mapper(BankAccount)

