// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  DeleteItemRouteBankAccountsItemIdDeleteData,
  DeleteItemRouteBankAccountsItemIdDeleteErrors,
  DeleteItemRouteBankAccountsItemIdDeleteResponses,
  DeleteItemRouteDecimalProvidersItemIdDeleteData,
  DeleteItemRouteDecimalProvidersItemIdDeleteErrors,
  DeleteItemRouteDecimalProvidersItemIdDeleteResponses,
  DeleteItemRouteEntitiesItemIdDeleteData,
  DeleteItemRouteEntitiesItemIdDeleteErrors,
  DeleteItemRouteEntitiesItemIdDeleteResponses,
  DeleteItemRouteLedgerAccountsItemIdDeleteData,
  DeleteItemRouteLedgerAccountsItemIdDeleteErrors,
  DeleteItemRouteLedgerAccountsItemIdDeleteResponses,
  DeleteItemRouteRateProvidersItemIdDeleteData,
  DeleteItemRouteRateProvidersItemIdDeleteErrors,
  DeleteItemRouteRateProvidersItemIdDeleteResponses,
  DeleteItemRouteRatesItemIdDeleteData,
  DeleteItemRouteRatesItemIdDeleteErrors,
  DeleteItemRouteRatesItemIdDeleteResponses,
  DeleteItemRouteScenariosItemIdDeleteData,
  DeleteItemRouteScenariosItemIdDeleteErrors,
  DeleteItemRouteScenariosItemIdDeleteResponses,
  DeleteItemRouteSchedulesItemIdDeleteData,
  DeleteItemRouteSchedulesItemIdDeleteErrors,
  DeleteItemRouteSchedulesItemIdDeleteResponses,
  GetDummyDaysGetData,
  GetDummyDaysGetErrors,
  GetDummyDaysGetResponses,
  GetItemRouteBankAccountsItemIdGetData,
  GetItemRouteBankAccountsItemIdGetErrors,
  GetItemRouteBankAccountsItemIdGetResponses,
  GetItemRouteDecimalProvidersItemIdGetData,
  GetItemRouteDecimalProvidersItemIdGetErrors,
  GetItemRouteDecimalProvidersItemIdGetResponses,
  GetItemRouteEntitiesItemIdGetData,
  GetItemRouteEntitiesItemIdGetErrors,
  GetItemRouteEntitiesItemIdGetResponses,
  GetItemRouteLedgerAccountsItemIdGetData,
  GetItemRouteLedgerAccountsItemIdGetErrors,
  GetItemRouteLedgerAccountsItemIdGetResponses,
  GetItemRouteRateProvidersItemIdGetData,
  GetItemRouteRateProvidersItemIdGetErrors,
  GetItemRouteRateProvidersItemIdGetResponses,
  GetItemRouteRatesItemIdGetData,
  GetItemRouteRatesItemIdGetErrors,
  GetItemRouteRatesItemIdGetResponses,
  GetItemRouteScenariosItemIdGetData,
  GetItemRouteScenariosItemIdGetErrors,
  GetItemRouteScenariosItemIdGetResponses,
  GetItemRouteSchedulesItemIdGetData,
  GetItemRouteSchedulesItemIdGetErrors,
  GetItemRouteSchedulesItemIdGetResponses,
  GetItemsRouteBankAccountsGetData,
  GetItemsRouteBankAccountsGetResponses,
  GetItemsRouteDecimalProvidersGetData,
  GetItemsRouteDecimalProvidersGetResponses,
  GetItemsRouteEntitiesGetData,
  GetItemsRouteEntitiesGetResponses,
  GetItemsRouteLedgerAccountsGetData,
  GetItemsRouteLedgerAccountsGetResponses,
  GetItemsRouteRateProvidersGetData,
  GetItemsRouteRateProvidersGetResponses,
  GetItemsRouteRatesGetData,
  GetItemsRouteRatesGetResponses,
  GetItemsRouteScenariosGetData,
  GetItemsRouteScenariosGetResponses,
  GetItemsRouteSchedulesGetData,
  GetItemsRouteSchedulesGetResponses,
  PostItemRouteBankAccountsPostData,
  PostItemRouteBankAccountsPostErrors,
  PostItemRouteBankAccountsPostResponses,
  PostItemRouteDecimalProvidersPostData,
  PostItemRouteDecimalProvidersPostErrors,
  PostItemRouteDecimalProvidersPostResponses,
  PostItemRouteEntitiesPostData,
  PostItemRouteEntitiesPostErrors,
  PostItemRouteEntitiesPostResponses,
  PostItemRouteLedgerAccountsPostData,
  PostItemRouteLedgerAccountsPostErrors,
  PostItemRouteLedgerAccountsPostResponses,
  PostItemRouteRateProvidersPostData,
  PostItemRouteRateProvidersPostErrors,
  PostItemRouteRateProvidersPostResponses,
  PostItemRouteRatesPostData,
  PostItemRouteRatesPostErrors,
  PostItemRouteRatesPostResponses,
  PostItemRouteScenariosPostData,
  PostItemRouteScenariosPostErrors,
  PostItemRouteScenariosPostResponses,
  PostItemRouteSchedulesPostData,
  PostItemRouteSchedulesPostErrors,
  PostItemRouteSchedulesPostResponses,
  PutItemRouteBankAccountsItemIdPutData,
  PutItemRouteBankAccountsItemIdPutErrors,
  PutItemRouteBankAccountsItemIdPutResponses,
  PutItemRouteDecimalProvidersItemIdPutData,
  PutItemRouteDecimalProvidersItemIdPutErrors,
  PutItemRouteDecimalProvidersItemIdPutResponses,
  PutItemRouteEntitiesItemIdPutData,
  PutItemRouteEntitiesItemIdPutErrors,
  PutItemRouteEntitiesItemIdPutResponses,
  PutItemRouteLedgerAccountsItemIdPutData,
  PutItemRouteLedgerAccountsItemIdPutErrors,
  PutItemRouteLedgerAccountsItemIdPutResponses,
  PutItemRouteRateProvidersItemIdPutData,
  PutItemRouteRateProvidersItemIdPutErrors,
  PutItemRouteRateProvidersItemIdPutResponses,
  PutItemRouteRatesItemIdPutData,
  PutItemRouteRatesItemIdPutErrors,
  PutItemRouteRatesItemIdPutResponses,
  PutItemRouteScenariosItemIdPutData,
  PutItemRouteScenariosItemIdPutErrors,
  PutItemRouteScenariosItemIdPutResponses,
  PutItemRouteSchedulesItemIdPutData,
  PutItemRouteSchedulesItemIdPutErrors,
  PutItemRouteSchedulesItemIdPutResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Items Route
 */
export const getItemsRouteScenariosGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetItemsRouteScenariosGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetItemsRouteScenariosGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/scenarios/",
    ...options,
  });
};

/**
 * Post Item Route
 */
export const postItemRouteScenariosPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostItemRouteScenariosPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostItemRouteScenariosPostResponses,
    PostItemRouteScenariosPostErrors,
    ThrowOnError
  >({
    url: "/scenarios/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteScenariosItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteItemRouteScenariosItemIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemRouteScenariosItemIdDeleteResponses,
    DeleteItemRouteScenariosItemIdDeleteErrors,
    ThrowOnError
  >({
    url: "/scenarios/{item_id}",
    ...options,
  });
};

/**
 * Get Item Route
 */
export const getItemRouteScenariosItemIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemRouteScenariosItemIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemRouteScenariosItemIdGetResponses,
    GetItemRouteScenariosItemIdGetErrors,
    ThrowOnError
  >({
    url: "/scenarios/{item_id}",
    ...options,
  });
};

/**
 * Put Item Route
 */
export const putItemRouteScenariosItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutItemRouteScenariosItemIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutItemRouteScenariosItemIdPutResponses,
    PutItemRouteScenariosItemIdPutErrors,
    ThrowOnError
  >({
    url: "/scenarios/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Items Route
 */
export const getItemsRouteEntitiesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetItemsRouteEntitiesGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetItemsRouteEntitiesGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/entities/",
    ...options,
  });
};

/**
 * Post Item Route
 */
export const postItemRouteEntitiesPost = <ThrowOnError extends boolean = false>(
  options: Options<PostItemRouteEntitiesPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostItemRouteEntitiesPostResponses,
    PostItemRouteEntitiesPostErrors,
    ThrowOnError
  >({
    url: "/entities/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteEntitiesItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteItemRouteEntitiesItemIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemRouteEntitiesItemIdDeleteResponses,
    DeleteItemRouteEntitiesItemIdDeleteErrors,
    ThrowOnError
  >({
    url: "/entities/{item_id}",
    ...options,
  });
};

/**
 * Get Item Route
 */
export const getItemRouteEntitiesItemIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemRouteEntitiesItemIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemRouteEntitiesItemIdGetResponses,
    GetItemRouteEntitiesItemIdGetErrors,
    ThrowOnError
  >({
    url: "/entities/{item_id}",
    ...options,
  });
};

/**
 * Put Item Route
 */
export const putItemRouteEntitiesItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutItemRouteEntitiesItemIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutItemRouteEntitiesItemIdPutResponses,
    PutItemRouteEntitiesItemIdPutErrors,
    ThrowOnError
  >({
    url: "/entities/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Items Route
 */
export const getItemsRouteBankAccountsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetItemsRouteBankAccountsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetItemsRouteBankAccountsGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/bank-accounts/",
    ...options,
  });
};

/**
 * Post Item Route
 */
export const postItemRouteBankAccountsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostItemRouteBankAccountsPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostItemRouteBankAccountsPostResponses,
    PostItemRouteBankAccountsPostErrors,
    ThrowOnError
  >({
    url: "/bank-accounts/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteBankAccountsItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteItemRouteBankAccountsItemIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemRouteBankAccountsItemIdDeleteResponses,
    DeleteItemRouteBankAccountsItemIdDeleteErrors,
    ThrowOnError
  >({
    url: "/bank-accounts/{item_id}",
    ...options,
  });
};

/**
 * Get Item Route
 */
export const getItemRouteBankAccountsItemIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemRouteBankAccountsItemIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemRouteBankAccountsItemIdGetResponses,
    GetItemRouteBankAccountsItemIdGetErrors,
    ThrowOnError
  >({
    url: "/bank-accounts/{item_id}",
    ...options,
  });
};

/**
 * Put Item Route
 */
export const putItemRouteBankAccountsItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutItemRouteBankAccountsItemIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutItemRouteBankAccountsItemIdPutResponses,
    PutItemRouteBankAccountsItemIdPutErrors,
    ThrowOnError
  >({
    url: "/bank-accounts/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Items Route
 */
export const getItemsRouteLedgerAccountsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetItemsRouteLedgerAccountsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetItemsRouteLedgerAccountsGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/ledger-accounts/",
    ...options,
  });
};

/**
 * Post Item Route
 */
export const postItemRouteLedgerAccountsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostItemRouteLedgerAccountsPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostItemRouteLedgerAccountsPostResponses,
    PostItemRouteLedgerAccountsPostErrors,
    ThrowOnError
  >({
    url: "/ledger-accounts/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteLedgerAccountsItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteItemRouteLedgerAccountsItemIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemRouteLedgerAccountsItemIdDeleteResponses,
    DeleteItemRouteLedgerAccountsItemIdDeleteErrors,
    ThrowOnError
  >({
    url: "/ledger-accounts/{item_id}",
    ...options,
  });
};

/**
 * Get Item Route
 */
export const getItemRouteLedgerAccountsItemIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemRouteLedgerAccountsItemIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemRouteLedgerAccountsItemIdGetResponses,
    GetItemRouteLedgerAccountsItemIdGetErrors,
    ThrowOnError
  >({
    url: "/ledger-accounts/{item_id}",
    ...options,
  });
};

/**
 * Put Item Route
 */
export const putItemRouteLedgerAccountsItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutItemRouteLedgerAccountsItemIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutItemRouteLedgerAccountsItemIdPutResponses,
    PutItemRouteLedgerAccountsItemIdPutErrors,
    ThrowOnError
  >({
    url: "/ledger-accounts/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Items Route
 */
export const getItemsRouteRatesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetItemsRouteRatesGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetItemsRouteRatesGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/rates/",
    ...options,
  });
};

/**
 * Post Item Route
 */
export const postItemRouteRatesPost = <ThrowOnError extends boolean = false>(
  options: Options<PostItemRouteRatesPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostItemRouteRatesPostResponses,
    PostItemRouteRatesPostErrors,
    ThrowOnError
  >({
    url: "/rates/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteRatesItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteItemRouteRatesItemIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemRouteRatesItemIdDeleteResponses,
    DeleteItemRouteRatesItemIdDeleteErrors,
    ThrowOnError
  >({
    url: "/rates/{item_id}",
    ...options,
  });
};

/**
 * Get Item Route
 */
export const getItemRouteRatesItemIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemRouteRatesItemIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemRouteRatesItemIdGetResponses,
    GetItemRouteRatesItemIdGetErrors,
    ThrowOnError
  >({
    url: "/rates/{item_id}",
    ...options,
  });
};

/**
 * Put Item Route
 */
export const putItemRouteRatesItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutItemRouteRatesItemIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutItemRouteRatesItemIdPutResponses,
    PutItemRouteRatesItemIdPutErrors,
    ThrowOnError
  >({
    url: "/rates/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Items Route
 */
export const getItemsRouteSchedulesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetItemsRouteSchedulesGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetItemsRouteSchedulesGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/schedules/",
    ...options,
  });
};

/**
 * Post Item Route
 */
export const postItemRouteSchedulesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostItemRouteSchedulesPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostItemRouteSchedulesPostResponses,
    PostItemRouteSchedulesPostErrors,
    ThrowOnError
  >({
    url: "/schedules/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteSchedulesItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteItemRouteSchedulesItemIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemRouteSchedulesItemIdDeleteResponses,
    DeleteItemRouteSchedulesItemIdDeleteErrors,
    ThrowOnError
  >({
    url: "/schedules/{item_id}",
    ...options,
  });
};

/**
 * Get Item Route
 */
export const getItemRouteSchedulesItemIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemRouteSchedulesItemIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemRouteSchedulesItemIdGetResponses,
    GetItemRouteSchedulesItemIdGetErrors,
    ThrowOnError
  >({
    url: "/schedules/{item_id}",
    ...options,
  });
};

/**
 * Put Item Route
 */
export const putItemRouteSchedulesItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutItemRouteSchedulesItemIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutItemRouteSchedulesItemIdPutResponses,
    PutItemRouteSchedulesItemIdPutErrors,
    ThrowOnError
  >({
    url: "/schedules/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Items Route
 */
export const getItemsRouteRateProvidersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetItemsRouteRateProvidersGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetItemsRouteRateProvidersGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/rate-providers/",
    ...options,
  });
};

/**
 * Post Item Route
 */
export const postItemRouteRateProvidersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostItemRouteRateProvidersPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostItemRouteRateProvidersPostResponses,
    PostItemRouteRateProvidersPostErrors,
    ThrowOnError
  >({
    url: "/rate-providers/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteRateProvidersItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteItemRouteRateProvidersItemIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemRouteRateProvidersItemIdDeleteResponses,
    DeleteItemRouteRateProvidersItemIdDeleteErrors,
    ThrowOnError
  >({
    url: "/rate-providers/{item_id}",
    ...options,
  });
};

/**
 * Get Item Route
 */
export const getItemRouteRateProvidersItemIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemRouteRateProvidersItemIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemRouteRateProvidersItemIdGetResponses,
    GetItemRouteRateProvidersItemIdGetErrors,
    ThrowOnError
  >({
    url: "/rate-providers/{item_id}",
    ...options,
  });
};

/**
 * Put Item Route
 */
export const putItemRouteRateProvidersItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutItemRouteRateProvidersItemIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutItemRouteRateProvidersItemIdPutResponses,
    PutItemRouteRateProvidersItemIdPutErrors,
    ThrowOnError
  >({
    url: "/rate-providers/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Items Route
 */
export const getItemsRouteDecimalProvidersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetItemsRouteDecimalProvidersGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetItemsRouteDecimalProvidersGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/decimal-providers/",
    ...options,
  });
};

/**
 * Post Item Route
 */
export const postItemRouteDecimalProvidersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostItemRouteDecimalProvidersPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostItemRouteDecimalProvidersPostResponses,
    PostItemRouteDecimalProvidersPostErrors,
    ThrowOnError
  >({
    url: "/decimal-providers/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteDecimalProvidersItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteItemRouteDecimalProvidersItemIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    DeleteItemRouteDecimalProvidersItemIdDeleteResponses,
    DeleteItemRouteDecimalProvidersItemIdDeleteErrors,
    ThrowOnError
  >({
    url: "/decimal-providers/{item_id}",
    ...options,
  });
};

/**
 * Get Item Route
 */
export const getItemRouteDecimalProvidersItemIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemRouteDecimalProvidersItemIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetItemRouteDecimalProvidersItemIdGetResponses,
    GetItemRouteDecimalProvidersItemIdGetErrors,
    ThrowOnError
  >({
    url: "/decimal-providers/{item_id}",
    ...options,
  });
};

/**
 * Put Item Route
 */
export const putItemRouteDecimalProvidersItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutItemRouteDecimalProvidersItemIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutItemRouteDecimalProvidersItemIdPutResponses,
    PutItemRouteDecimalProvidersItemIdPutErrors,
    ThrowOnError
  >({
    url: "/decimal-providers/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get
 */
export const getDummyDaysGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetDummyDaysGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).sse.get<
    GetDummyDaysGetResponses,
    GetDummyDaysGetErrors,
    ThrowOnError
  >({
    url: "/dummy-days/",
    ...options,
  });
};
