"""initialize

Revision ID: ec83af98fb40
Revises: 
Create Date: 2025-09-26 18:43:52.332204

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ec83af98fb40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity')),
    sa.UniqueConstraint('name', name=op.f('uq_entity_name'))
    )
    op.create_table('scenario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario')),
    sa.UniqueConstraint('name', name=op.f('uq_scenario_name'))
    )
    op.create_table('scenario_entity',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_scenario_entity_entity_id_entity')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], name=op.f('fk_scenario_entity_scenario_id_scenario')),
    sa.PrimaryKeyConstraint('scenario_id', 'entity_id', name=op.f('pk_scenario_entity'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_entity')
    op.drop_table('scenario')
    op.drop_table('entity')
    # ### end Alembic commands ###
