from financial_simulator.app.database.schema import LedgerAccount
from financial_simulator.app.server.util.dependent import create_dependent_get_mapper

ledger_account_dependent_get_mapper = create_dependent_get_mapper(LedgerAccount)

