"""fix_cascade_deletes_again

Revision ID: 10af095ec839
Revises: 7c1875587ad1
Create Date: 2025-10-21 13:18:06.084453

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '10af095ec839'
down_revision: Union[str, Sequence[str], None] = '7c1875587ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
