"""use enums for polymorphic types

Revision ID: 1c1c8710dfc9
Revises: 82e26cdbfbc3
Create Date: 2025-11-23 18:39:23.369039

"""
from typing import Sequence, Union
from uuid import UUID

from alembic import op
from sqlalchemy import orm
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import mapped_column, Mapped

# revision identifiers, used by Alembic.
revision: str = '1c1c8710dfc9'
down_revision: Union[str, Sequence[str], None] = '82e26cdbfbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

Base = declarative_base()


class Entity(Base):
    __tablename__ = 'entity'
    id: Mapped[UUID] = mapped_column(primary_key=True)
    type: Mapped[str] = mapped_column()

entity_type_upgrade_map = {
    "individual_entity": "INDIVIDUAL",
    "corporation_entity": "CORPORATION",
}
entity_type_downgrade_map = {v: k for k, v in entity_type_upgrade_map.items()}

class Rate(Base):
    __tablename__ = 'rate'
    id: Mapped[UUID] = mapped_column(primary_key=True)
    type: Mapped[str] = mapped_column()

rate_type_upgrade_map = {
    "periodic_rate": "PERIODIC",
    "continuous_rate": "CONTINUOUS",
    "banded_rate": "BANDED",
}
rate_type_downgrade_map = {v: k for k, v in rate_type_upgrade_map.items()}


class Value(Base):
    __tablename__ = 'value'
    id: Mapped[UUID] = mapped_column(primary_key=True)
    type: Mapped[str] = mapped_column()

value_type_upgrade_map = {
    "decimal_value": "DECIMAL",
    "rate_value": "RATE",
}
value_type_downgrade_map = {v: k for k, v in value_type_upgrade_map.items()}


class Schedule(Base):
    __tablename__ = 'schedule'
    id: Mapped[UUID] = mapped_column(primary_key=True)
    type: Mapped[str] = mapped_column()

schedule_type_upgrade_map = {
    "all_schedule": "ALL",
    "any_schedule": "ANY",
    "daily_schedule": "DAILY",
    "day_schedule": "DAY",
    "weekly_schedule": "WEEKLY",
    "monthly_schedule": "MONTHLY",
    "yearly_schedule": "YEARLY",
    "from_schedule": "FROM",
    "until_schedule": "UNTIL",
    "range_schedule": "RANGE",
}
schedule_type_downgrade_map = {v: k for k, v in schedule_type_upgrade_map.items()}


class Provider(Base):
    __tablename__ = 'provider'
    id: Mapped[UUID] = mapped_column(primary_key=True)
    type: Mapped[str] = mapped_column()

provider_type_upgrade_map = {
    "merge_provider": "MERGE",
    "next_provider": "NEXT",
    "always_provider": "ALWAYS",
    "scheduled_provider": "SCHEDULED",
}
provider_type_downgrade_map = {v: k for k, v in provider_type_upgrade_map.items()}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    for row in session.query(Entity).all():
        row.type = entity_type_upgrade_map[str(row.type)]
    for row in session.query(Rate).all():
        row.type = rate_type_upgrade_map[str(row.type)]
    for row in session.query(Value).all():
        row.type = value_type_upgrade_map[str(row.type)]
    for row in session.query(Schedule).all():
        row.type = schedule_type_upgrade_map[str(row.type)]
    for row in session.query(Provider).all():
        row.type = provider_type_upgrade_map[str(row.type)]
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    for row in session.query(Entity).all():
        row.type = entity_type_downgrade_map[str(row.type)]
    for row in session.query(Rate).all():
        row.type = rate_type_downgrade_map[str(row.type)]
    for row in session.query(Value).all():
        row.type = value_type_downgrade_map[str(row.type)]
    for row in session.query(Schedule).all():
        row.type = schedule_type_downgrade_map[str(row.type)]
    for row in session.query(Provider).all():
        row.type = provider_type_downgrade_map[str(row.type)]
    session.commit()
