"""cascade_deletes

Revision ID: 37feb0c81451
Revises: 0b60e1c7e04b
Create Date: 2025-10-21 11:49:50.322334

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '37feb0c81451'
down_revision: Union[str, Sequence[str], None] = '0b60e1c7e04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
