"""init

Revision ID: 3850b1fa6196
Revises: 
Create Date: 2025-12-16 13:00:28.550690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3850b1fa6196'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decimal_provider',
    sa.Column('type', sa.Enum('SCHEDULED', 'MERGE', 'NEXT', name='decimalprovidertype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decimal_provider')),
    sa.UniqueConstraint('name', name=op.f('uq_decimal_provider_name'))
    )
    op.create_table('entity',
    sa.Column('type', sa.Enum('INDIVIDUAL', 'CORPORATION', name='entitytype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity')),
    sa.UniqueConstraint('name', name=op.f('uq_entity_name'))
    )
    op.create_table('ledger_account',
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ledger_account.id'], name=op.f('fk_ledger_account_parent_id_ledger_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_account')),
    sa.UniqueConstraint('name', name=op.f('uq_ledger_account_name')),
    sa.UniqueConstraint('parent_id', 'account_name', name=op.f('uq_ledger_account_parent_id'))
    )
    op.create_table('rate',
    sa.Column('type', sa.Enum('PERIODIC', 'CONTINUOUS', 'BANDED', name='ratetype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate')),
    sa.UniqueConstraint('name', name=op.f('uq_rate_name'))
    )
    op.create_table('rate_provider',
    sa.Column('type', sa.Enum('SCHEDULED', 'MERGE', 'NEXT', name='rateprovidertype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_provider')),
    sa.UniqueConstraint('name', name=op.f('uq_rate_provider_name'))
    )
    op.create_table('scenario',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario')),
    sa.UniqueConstraint('name', name=op.f('uq_scenario_name'))
    )
    op.create_table('schedule',
    sa.Column('type', sa.Enum('DAILY', 'DAY', 'FROM', 'MONTHLY', 'RANGE', 'UNTIL', 'WEEKLY', 'YEARLY', 'ALL', 'ANY', name='scheduletype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule')),
    sa.UniqueConstraint('name', name=op.f('uq_schedule_name'))
    )
    op.create_table('all_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_all_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_all_schedule'))
    )
    op.create_table('any_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_any_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_any_schedule'))
    )
    op.create_table('banded_rate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['rate.id'], name=op.f('fk_banded_rate_id_rate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banded_rate'))
    )
    op.create_table('bank_account',
    sa.Column('asset_account_id', sa.Uuid(), nullable=True),
    sa.Column('interest_income_account_id', sa.Uuid(), nullable=True),
    sa.Column('interest_receivable_account_id', sa.Uuid(), nullable=True),
    sa.Column('fee_expenses_account_id', sa.Uuid(), nullable=True),
    sa.Column('fees_payable_account_id', sa.Uuid(), nullable=True),
    sa.Column('fees_provider_id', sa.Uuid(), nullable=True),
    sa.Column('fee_payment_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('interest_rate_provider_id', sa.Uuid(), nullable=True),
    sa.Column('interest_payment_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_account_id'], ['ledger_account.id'], name=op.f('fk_bank_account_asset_account_id_ledger_account')),
    sa.ForeignKeyConstraint(['fee_expenses_account_id'], ['ledger_account.id'], name=op.f('fk_bank_account_fee_expenses_account_id_ledger_account')),
    sa.ForeignKeyConstraint(['fee_payment_schedule_id'], ['schedule.id'], name=op.f('fk_bank_account_fee_payment_schedule_id_schedule')),
    sa.ForeignKeyConstraint(['fees_payable_account_id'], ['ledger_account.id'], name=op.f('fk_bank_account_fees_payable_account_id_ledger_account')),
    sa.ForeignKeyConstraint(['fees_provider_id'], ['decimal_provider.id'], name=op.f('fk_bank_account_fees_provider_id_decimal_provider')),
    sa.ForeignKeyConstraint(['interest_income_account_id'], ['ledger_account.id'], name=op.f('fk_bank_account_interest_income_account_id_ledger_account')),
    sa.ForeignKeyConstraint(['interest_payment_schedule_id'], ['schedule.id'], name=op.f('fk_bank_account_interest_payment_schedule_id_schedule')),
    sa.ForeignKeyConstraint(['interest_rate_provider_id'], ['rate_provider.id'], name=op.f('fk_bank_account_interest_rate_provider_id_rate_provider')),
    sa.ForeignKeyConstraint(['interest_receivable_account_id'], ['ledger_account.id'], name=op.f('fk_bank_account_interest_receivable_account_id_ledger_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_account')),
    sa.UniqueConstraint('name', name=op.f('uq_bank_account_name'))
    )
    op.create_table('continuous_rate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('annual_rate', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['rate.id'], name=op.f('fk_continuous_rate_id_rate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_continuous_rate'))
    )
    op.create_table('corporation_entity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity.id'], name=op.f('fk_corporation_entity_id_entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporation_entity'))
    )
    op.create_table('daily_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_daily_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_schedule'))
    )
    op.create_table('day_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_day_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_day_schedule'))
    )
    op.create_table('from_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_from_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_from_schedule'))
    )
    op.create_table('individual_entity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity.id'], name=op.f('fk_individual_entity_id_entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_individual_entity'))
    )
    op.create_table('merge_decimal_provider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['decimal_provider.id'], name=op.f('fk_merge_decimal_provider_id_decimal_provider')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merge_decimal_provider'))
    )
    op.create_table('merge_rate_provider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['rate_provider.id'], name=op.f('fk_merge_rate_provider_id_rate_provider')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merge_rate_provider'))
    )
    op.create_table('monthly_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_monthly_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_schedule'))
    )
    op.create_table('next_decimal_provider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['decimal_provider.id'], name=op.f('fk_next_decimal_provider_id_decimal_provider')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_next_decimal_provider'))
    )
    op.create_table('next_rate_provider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['rate_provider.id'], name=op.f('fk_next_rate_provider_id_rate_provider')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_next_rate_provider'))
    )
    op.create_table('periodic_rate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('annual_rate', sa.Numeric(), nullable=True),
    sa.Column('period_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['rate.id'], name=op.f('fk_periodic_rate_id_rate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_periodic_rate'))
    )
    op.create_table('range_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('until_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_range_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_range_schedule'))
    )
    op.create_table('scenario_entity',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_scenario_entity_entity_id_entity')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], name=op.f('fk_scenario_entity_scenario_id_scenario')),
    sa.PrimaryKeyConstraint('scenario_id', 'entity_id', name=op.f('pk_scenario_entity'))
    )
    op.create_table('scheduled_decimal_provider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['decimal_provider.id'], name=op.f('fk_scheduled_decimal_provider_id_decimal_provider')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name=op.f('fk_scheduled_decimal_provider_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_decimal_provider'))
    )
    op.create_table('scheduled_rate_provider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rate_id', sa.Uuid(), nullable=True),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['rate_provider.id'], name=op.f('fk_scheduled_rate_provider_id_rate_provider')),
    sa.ForeignKeyConstraint(['rate_id'], ['rate.id'], name=op.f('fk_scheduled_rate_provider_rate_id_rate')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name=op.f('fk_scheduled_rate_provider_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_rate_provider'))
    )
    op.create_table('until_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('until_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_until_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_until_schedule'))
    )
    op.create_table('weekly_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_weekly_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_schedule'))
    )
    op.create_table('yearly_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_yearly_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yearly_schedule'))
    )
    op.create_table('all_schedule_schedule',
    sa.Column('all_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['all_schedule_id'], ['all_schedule.id'], name=op.f('fk_all_schedule_schedule_all_schedule_id_all_schedule')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name=op.f('fk_all_schedule_schedule_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('all_schedule_id', 'schedule_id', name=op.f('pk_all_schedule_schedule'))
    )
    op.create_table('any_schedule_schedule',
    sa.Column('any_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['any_schedule_id'], ['any_schedule.id'], name=op.f('fk_any_schedule_schedule_any_schedule_id_any_schedule')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name=op.f('fk_any_schedule_schedule_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('any_schedule_id', 'schedule_id', name=op.f('pk_any_schedule_schedule'))
    )
    op.create_table('banded_rate_bands',
    sa.Column('banded_rate_id', sa.Uuid(), nullable=False),
    sa.Column('remainder_rate_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['banded_rate_id'], ['banded_rate.id'], name=op.f('fk_banded_rate_bands_banded_rate_id_banded_rate')),
    sa.ForeignKeyConstraint(['remainder_rate_id'], ['rate.id'], name=op.f('fk_banded_rate_bands_remainder_rate_id_rate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banded_rate_bands'))
    )
    op.create_table('corporation_entity_bank_account',
    sa.Column('corporation_entity_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('fk_corporation_entity_bank_account_bank_account_id_bank_account')),
    sa.ForeignKeyConstraint(['corporation_entity_id'], ['corporation_entity.id'], name=op.f('fk_corporation_entity_bank_account_corporation_entity_id_corporation_entity')),
    sa.PrimaryKeyConstraint('corporation_entity_id', 'bank_account_id', name=op.f('pk_corporation_entity_bank_account'))
    )
    op.create_table('individual_entity_bank_account',
    sa.Column('individual_entity_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('fk_individual_entity_bank_account_bank_account_id_bank_account')),
    sa.ForeignKeyConstraint(['individual_entity_id'], ['individual_entity.id'], name=op.f('fk_individual_entity_bank_account_individual_entity_id_individual_entity')),
    sa.PrimaryKeyConstraint('individual_entity_id', 'bank_account_id', name=op.f('pk_individual_entity_bank_account'))
    )
    op.create_table('merge_decimal_provider_provider',
    sa.Column('merge_decimal_provider_id', sa.Uuid(), nullable=False),
    sa.Column('decimal_provider_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decimal_provider_id'], ['decimal_provider.id'], name=op.f('fk_merge_decimal_provider_provider_decimal_provider_id_decimal_provider')),
    sa.ForeignKeyConstraint(['merge_decimal_provider_id'], ['merge_decimal_provider.id'], name=op.f('fk_merge_decimal_provider_provider_merge_decimal_provider_id_merge_decimal_provider')),
    sa.PrimaryKeyConstraint('merge_decimal_provider_id', 'decimal_provider_id', name=op.f('pk_merge_decimal_provider_provider'))
    )
    op.create_table('merge_rate_provider_provider',
    sa.Column('merge_rate_provider_id', sa.Uuid(), nullable=False),
    sa.Column('rate_provider_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merge_rate_provider_id'], ['merge_rate_provider.id'], name=op.f('fk_merge_rate_provider_provider_merge_rate_provider_id_merge_rate_provider')),
    sa.ForeignKeyConstraint(['rate_provider_id'], ['rate_provider.id'], name=op.f('fk_merge_rate_provider_provider_rate_provider_id_rate_provider')),
    sa.PrimaryKeyConstraint('merge_rate_provider_id', 'rate_provider_id', name=op.f('pk_merge_rate_provider_provider'))
    )
    op.create_table('next_decimal_provider_provider',
    sa.Column('next_decimal_provider_id', sa.Uuid(), nullable=False),
    sa.Column('decimal_provider_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decimal_provider_id'], ['decimal_provider.id'], name=op.f('fk_next_decimal_provider_provider_decimal_provider_id_decimal_provider')),
    sa.ForeignKeyConstraint(['next_decimal_provider_id'], ['next_decimal_provider.id'], name=op.f('fk_next_decimal_provider_provider_next_decimal_provider_id_next_decimal_provider')),
    sa.PrimaryKeyConstraint('next_decimal_provider_id', 'decimal_provider_id', name=op.f('pk_next_decimal_provider_provider'))
    )
    op.create_table('next_rate_provider_provider',
    sa.Column('next_rate_provider_id', sa.Uuid(), nullable=False),
    sa.Column('rate_provider_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['next_rate_provider_id'], ['next_rate_provider.id'], name=op.f('fk_next_rate_provider_provider_next_rate_provider_id_next_rate_provider')),
    sa.ForeignKeyConstraint(['rate_provider_id'], ['rate_provider.id'], name=op.f('fk_next_rate_provider_provider_rate_provider_id_rate_provider')),
    sa.PrimaryKeyConstraint('next_rate_provider_id', 'rate_provider_id', name=op.f('pk_next_rate_provider_provider'))
    )
    op.create_table('banded_rate_band',
    sa.Column('banded_rate_bands_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('size', sa.Numeric(), nullable=True),
    sa.Column('rate_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['banded_rate_bands_id'], ['banded_rate_bands.id'], name=op.f('fk_banded_rate_band_banded_rate_bands_id_banded_rate_bands')),
    sa.ForeignKeyConstraint(['rate_id'], ['rate.id'], name=op.f('fk_banded_rate_band_rate_id_rate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banded_rate_band'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banded_rate_band')
    op.drop_table('next_rate_provider_provider')
    op.drop_table('next_decimal_provider_provider')
    op.drop_table('merge_rate_provider_provider')
    op.drop_table('merge_decimal_provider_provider')
    op.drop_table('individual_entity_bank_account')
    op.drop_table('corporation_entity_bank_account')
    op.drop_table('banded_rate_bands')
    op.drop_table('any_schedule_schedule')
    op.drop_table('all_schedule_schedule')
    op.drop_table('yearly_schedule')
    op.drop_table('weekly_schedule')
    op.drop_table('until_schedule')
    op.drop_table('scheduled_rate_provider')
    op.drop_table('scheduled_decimal_provider')
    op.drop_table('scenario_entity')
    op.drop_table('range_schedule')
    op.drop_table('periodic_rate')
    op.drop_table('next_rate_provider')
    op.drop_table('next_decimal_provider')
    op.drop_table('monthly_schedule')
    op.drop_table('merge_rate_provider')
    op.drop_table('merge_decimal_provider')
    op.drop_table('individual_entity')
    op.drop_table('from_schedule')
    op.drop_table('day_schedule')
    op.drop_table('daily_schedule')
    op.drop_table('corporation_entity')
    op.drop_table('continuous_rate')
    op.drop_table('bank_account')
    op.drop_table('banded_rate')
    op.drop_table('any_schedule')
    op.drop_table('all_schedule')
    op.drop_table('schedule')
    op.drop_table('scenario')
    op.drop_table('rate_provider')
    op.drop_table('rate')
    op.drop_table('ledger_account')
    op.drop_table('entity')
    op.drop_table('decimal_provider')
    # ### end Alembic commands ###
