"""ordered rate bands providers and schedules

Revision ID: 82e26cdbfbc3
Revises: c4cf126fed0a
Create Date: 2025-11-18 09:36:12.823259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e26cdbfbc3'
down_revision: Union[str, Sequence[str], None] = 'c4cf126fed0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('from_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_from_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_from_schedule'))
    )
    op.create_table('monthly_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_monthly_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_schedule'))
    )
    op.create_table('range_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('until_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_range_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_range_schedule'))
    )
    op.create_table('until_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('until_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_until_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_until_schedule'))
    )
    op.create_table('weekly_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_weekly_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_schedule'))
    )
    op.create_table('yearly_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule.id'], name=op.f('fk_yearly_schedule_id_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yearly_schedule'))
    )
    with op.batch_alter_table('all_schedule_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    with op.batch_alter_table('any_schedule_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    with op.batch_alter_table('banded_rate_band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))
        batch_op.drop_column('lower_bound')

    with op.batch_alter_table('merge_provider_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    with op.batch_alter_table('next_provider_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('next_provider_provider', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('merge_provider_provider', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('banded_rate_band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lower_bound', sa.NUMERIC(), nullable=True))
        batch_op.drop_column('position')

    with op.batch_alter_table('any_schedule_schedule', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('all_schedule_schedule', schema=None) as batch_op:
        batch_op.drop_column('position')

    op.drop_table('yearly_schedule')
    op.drop_table('weekly_schedule')
    op.drop_table('until_schedule')
    op.drop_table('range_schedule')
    op.drop_table('monthly_schedule')
    op.drop_table('from_schedule')
    # ### end Alembic commands ###
