// This file is auto-generated by @hey-api/openapi-ts

import type {Client, Options as Options2, TDataShape} from './client';
import {client} from './client.gen';
import type {
    DeleteItemRouteBankAccountsItemIdDeleteData,
    DeleteItemRouteBankAccountsItemIdDeleteErrors,
    DeleteItemRouteBankAccountsItemIdDeleteResponses,
    DeleteItemRouteEntitiesItemIdDeleteData,
    DeleteItemRouteEntitiesItemIdDeleteErrors,
    DeleteItemRouteEntitiesItemIdDeleteResponses,
    DeleteItemRouteLedgerAccountsItemIdDeleteData,
    DeleteItemRouteLedgerAccountsItemIdDeleteErrors,
    DeleteItemRouteLedgerAccountsItemIdDeleteResponses,
    DeleteItemRouteScenariosItemIdDeleteData,
    DeleteItemRouteScenariosItemIdDeleteErrors,
    DeleteItemRouteScenariosItemIdDeleteResponses,
    DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteData,
    DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteErrors,
    DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteResponses,
    DeleteRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdDeleteData,
    DeleteRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdDeleteErrors,
    DeleteRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdDeleteResponses,
    DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteData,
    DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteErrors,
    DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteResponses,
    GetDummyDaysGetData,
    GetDummyDaysGetErrors,
    GetDummyDaysGetResponses,
    GetItemRouteBankAccountsItemIdGetData,
    GetItemRouteBankAccountsItemIdGetErrors,
    GetItemRouteBankAccountsItemIdGetResponses,
    GetItemRouteEntitiesItemIdGetData,
    GetItemRouteEntitiesItemIdGetErrors,
    GetItemRouteEntitiesItemIdGetResponses,
    GetItemRouteLedgerAccountsItemIdGetData,
    GetItemRouteLedgerAccountsItemIdGetErrors,
    GetItemRouteLedgerAccountsItemIdGetResponses,
    GetItemRouteScenariosItemIdGetData,
    GetItemRouteScenariosItemIdGetErrors,
    GetItemRouteScenariosItemIdGetResponses,
    GetItemsRouteBankAccountsGetData,
    GetItemsRouteBankAccountsGetErrors,
    GetItemsRouteBankAccountsGetResponses,
    GetItemsRouteEntitiesGetData,
    GetItemsRouteEntitiesGetErrors,
    GetItemsRouteEntitiesGetResponses,
    GetItemsRouteLedgerAccountsGetData,
    GetItemsRouteLedgerAccountsGetErrors,
    GetItemsRouteLedgerAccountsGetResponses,
    GetItemsRouteScenariosGetData,
    GetItemsRouteScenariosGetErrors,
    GetItemsRouteScenariosGetResponses,
    GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetData,
    GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetErrors,
    GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetResponses,
    GetRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdGetData,
    GetRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdGetErrors,
    GetRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdGetResponses,
    GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetData,
    GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetErrors,
    GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetResponses,
    GetRelatedItemsRouteEntitiesItemIdScenariosGetData,
    GetRelatedItemsRouteEntitiesItemIdScenariosGetErrors,
    GetRelatedItemsRouteEntitiesItemIdScenariosGetResponses,
    GetRelatedItemsRouteLedgerAccountsItemIdSubAccountsGetData,
    GetRelatedItemsRouteLedgerAccountsItemIdSubAccountsGetErrors,
    GetRelatedItemsRouteLedgerAccountsItemIdSubAccountsGetResponses,
    GetRelatedItemsRouteScenariosItemIdEntitiesGetData,
    GetRelatedItemsRouteScenariosItemIdEntitiesGetErrors,
    GetRelatedItemsRouteScenariosItemIdEntitiesGetResponses,
    PatchItemRouteBankAccountsItemIdPatchData,
    PatchItemRouteBankAccountsItemIdPatchErrors,
    PatchItemRouteBankAccountsItemIdPatchResponses,
    PatchItemRouteEntitiesItemIdPatchData,
    PatchItemRouteEntitiesItemIdPatchErrors,
    PatchItemRouteEntitiesItemIdPatchResponses,
    PatchItemRouteLedgerAccountsItemIdPatchData,
    PatchItemRouteLedgerAccountsItemIdPatchErrors,
    PatchItemRouteLedgerAccountsItemIdPatchResponses,
    PatchItemRouteScenariosItemIdPatchData,
    PatchItemRouteScenariosItemIdPatchErrors,
    PatchItemRouteScenariosItemIdPatchResponses,
    PostItemRouteBankAccountsPostData,
    PostItemRouteBankAccountsPostErrors,
    PostItemRouteBankAccountsPostResponses,
    PostItemRouteEntitiesPostData,
    PostItemRouteEntitiesPostErrors,
    PostItemRouteEntitiesPostResponses,
    PostItemRouteLedgerAccountsPostData,
    PostItemRouteLedgerAccountsPostErrors,
    PostItemRouteLedgerAccountsPostResponses,
    PostItemRouteScenariosPostData,
    PostItemRouteScenariosPostErrors,
    PostItemRouteScenariosPostResponses,
    PostRelatedItemRouteEntitiesItemIdScenariosPostData,
    PostRelatedItemRouteEntitiesItemIdScenariosPostErrors,
    PostRelatedItemRouteEntitiesItemIdScenariosPostResponses,
    PostRelatedItemRouteLedgerAccountsItemIdSubAccountsPostData,
    PostRelatedItemRouteLedgerAccountsItemIdSubAccountsPostErrors,
    PostRelatedItemRouteLedgerAccountsItemIdSubAccountsPostResponses,
    PostRelatedItemRouteScenariosItemIdEntitiesPostData,
    PostRelatedItemRouteScenariosItemIdEntitiesPostErrors,
    PostRelatedItemRouteScenariosItemIdEntitiesPostResponses,
    PutItemRouteBankAccountsItemIdPutData,
    PutItemRouteBankAccountsItemIdPutErrors,
    PutItemRouteBankAccountsItemIdPutResponses,
    PutItemRouteEntitiesItemIdPutData,
    PutItemRouteEntitiesItemIdPutErrors,
    PutItemRouteEntitiesItemIdPutResponses,
    PutItemRouteLedgerAccountsItemIdPutData,
    PutItemRouteLedgerAccountsItemIdPutErrors,
    PutItemRouteLedgerAccountsItemIdPutResponses,
    PutItemRouteScenariosItemIdPutData,
    PutItemRouteScenariosItemIdPutErrors,
    PutItemRouteScenariosItemIdPutResponses
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> =
    Options2<TData, ThrowOnError>
    & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Items Route
 */
export const getItemsRouteScenariosGet = <ThrowOnError extends boolean = false>(options?: Options<GetItemsRouteScenariosGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetItemsRouteScenariosGetResponses, GetItemsRouteScenariosGetErrors, ThrowOnError>({
        url: '/scenarios/',
        ...options
    });
};

/**
 * Post Item Route
 */
export const postItemRouteScenariosPost = <ThrowOnError extends boolean = false>(options: Options<PostItemRouteScenariosPostData, ThrowOnError>) => {
    return (options.client ?? client).post<PostItemRouteScenariosPostResponses, PostItemRouteScenariosPostErrors, ThrowOnError>({
        url: '/scenarios/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteScenariosItemIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteItemRouteScenariosItemIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteItemRouteScenariosItemIdDeleteResponses, DeleteItemRouteScenariosItemIdDeleteErrors, ThrowOnError>({
        url: '/scenarios/{item_id}',
        ...options
    });
};

/**
 * Get Item Route
 */
export const getItemRouteScenariosItemIdGet = <ThrowOnError extends boolean = false>(options: Options<GetItemRouteScenariosItemIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetItemRouteScenariosItemIdGetResponses, GetItemRouteScenariosItemIdGetErrors, ThrowOnError>({
        url: '/scenarios/{item_id}',
        ...options
    });
};

/**
 * Patch Item Route
 */
export const patchItemRouteScenariosItemIdPatch = <ThrowOnError extends boolean = false>(options: Options<PatchItemRouteScenariosItemIdPatchData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchItemRouteScenariosItemIdPatchResponses, PatchItemRouteScenariosItemIdPatchErrors, ThrowOnError>({
        url: '/scenarios/{item_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Put Item Route
 */
export const putItemRouteScenariosItemIdPut = <ThrowOnError extends boolean = false>(options: Options<PutItemRouteScenariosItemIdPutData, ThrowOnError>) => {
    return (options.client ?? client).put<PutItemRouteScenariosItemIdPutResponses, PutItemRouteScenariosItemIdPutErrors, ThrowOnError>({
        url: '/scenarios/{item_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Related Items Route
 */
export const getRelatedItemsRouteScenariosItemIdEntitiesGet = <ThrowOnError extends boolean = false>(options: Options<GetRelatedItemsRouteScenariosItemIdEntitiesGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRelatedItemsRouteScenariosItemIdEntitiesGetResponses, GetRelatedItemsRouteScenariosItemIdEntitiesGetErrors, ThrowOnError>({
        url: '/scenarios/{item_id}/entities/',
        ...options
    });
};

/**
 * Post Related Item Route
 */
export const postRelatedItemRouteScenariosItemIdEntitiesPost = <ThrowOnError extends boolean = false>(options: Options<PostRelatedItemRouteScenariosItemIdEntitiesPostData, ThrowOnError>) => {
    return (options.client ?? client).post<PostRelatedItemRouteScenariosItemIdEntitiesPostResponses, PostRelatedItemRouteScenariosItemIdEntitiesPostErrors, ThrowOnError>({
        url: '/scenarios/{item_id}/entities/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Related Item Route
 */
export const deleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteResponses, DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteErrors, ThrowOnError>({
        url: '/scenarios/{item_id}/entities/{related_item_id}',
        ...options
    });
};

/**
 * Get Related Item Route
 */
export const getRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGet = <ThrowOnError extends boolean = false>(options: Options<GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetResponses, GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetErrors, ThrowOnError>({
        url: '/scenarios/{item_id}/entities/{related_item_id}',
        ...options
    });
};

/**
 * Get Items Route
 */
export const getItemsRouteEntitiesGet = <ThrowOnError extends boolean = false>(options?: Options<GetItemsRouteEntitiesGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetItemsRouteEntitiesGetResponses, GetItemsRouteEntitiesGetErrors, ThrowOnError>({
        url: '/entities/',
        ...options
    });
};

/**
 * Post Item Route
 */
export const postItemRouteEntitiesPost = <ThrowOnError extends boolean = false>(options: Options<PostItemRouteEntitiesPostData, ThrowOnError>) => {
    return (options.client ?? client).post<PostItemRouteEntitiesPostResponses, PostItemRouteEntitiesPostErrors, ThrowOnError>({
        url: '/entities/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteEntitiesItemIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteItemRouteEntitiesItemIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteItemRouteEntitiesItemIdDeleteResponses, DeleteItemRouteEntitiesItemIdDeleteErrors, ThrowOnError>({
        url: '/entities/{item_id}',
        ...options
    });
};

/**
 * Get Item Route
 */
export const getItemRouteEntitiesItemIdGet = <ThrowOnError extends boolean = false>(options: Options<GetItemRouteEntitiesItemIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetItemRouteEntitiesItemIdGetResponses, GetItemRouteEntitiesItemIdGetErrors, ThrowOnError>({
        url: '/entities/{item_id}',
        ...options
    });
};

/**
 * Patch Item Route
 */
export const patchItemRouteEntitiesItemIdPatch = <ThrowOnError extends boolean = false>(options: Options<PatchItemRouteEntitiesItemIdPatchData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchItemRouteEntitiesItemIdPatchResponses, PatchItemRouteEntitiesItemIdPatchErrors, ThrowOnError>({
        url: '/entities/{item_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Put Item Route
 */
export const putItemRouteEntitiesItemIdPut = <ThrowOnError extends boolean = false>(options: Options<PutItemRouteEntitiesItemIdPutData, ThrowOnError>) => {
    return (options.client ?? client).put<PutItemRouteEntitiesItemIdPutResponses, PutItemRouteEntitiesItemIdPutErrors, ThrowOnError>({
        url: '/entities/{item_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Related Items Route
 */
export const getRelatedItemsRouteEntitiesItemIdScenariosGet = <ThrowOnError extends boolean = false>(options: Options<GetRelatedItemsRouteEntitiesItemIdScenariosGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRelatedItemsRouteEntitiesItemIdScenariosGetResponses, GetRelatedItemsRouteEntitiesItemIdScenariosGetErrors, ThrowOnError>({
        url: '/entities/{item_id}/scenarios/',
        ...options
    });
};

/**
 * Post Related Item Route
 */
export const postRelatedItemRouteEntitiesItemIdScenariosPost = <ThrowOnError extends boolean = false>(options: Options<PostRelatedItemRouteEntitiesItemIdScenariosPostData, ThrowOnError>) => {
    return (options.client ?? client).post<PostRelatedItemRouteEntitiesItemIdScenariosPostResponses, PostRelatedItemRouteEntitiesItemIdScenariosPostErrors, ThrowOnError>({
        url: '/entities/{item_id}/scenarios/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Related Item Route
 */
export const deleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteResponses, DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteErrors, ThrowOnError>({
        url: '/entities/{item_id}/scenarios/{related_item_id}',
        ...options
    });
};

/**
 * Get Related Item Route
 */
export const getRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGet = <ThrowOnError extends boolean = false>(options: Options<GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetResponses, GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetErrors, ThrowOnError>({
        url: '/entities/{item_id}/scenarios/{related_item_id}',
        ...options
    });
};

/**
 * Get Items Route
 */
export const getItemsRouteBankAccountsGet = <ThrowOnError extends boolean = false>(options?: Options<GetItemsRouteBankAccountsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetItemsRouteBankAccountsGetResponses, GetItemsRouteBankAccountsGetErrors, ThrowOnError>({
        url: '/bank-accounts/',
        ...options
    });
};

/**
 * Post Item Route
 */
export const postItemRouteBankAccountsPost = <ThrowOnError extends boolean = false>(options: Options<PostItemRouteBankAccountsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<PostItemRouteBankAccountsPostResponses, PostItemRouteBankAccountsPostErrors, ThrowOnError>({
        url: '/bank-accounts/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteBankAccountsItemIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteItemRouteBankAccountsItemIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteItemRouteBankAccountsItemIdDeleteResponses, DeleteItemRouteBankAccountsItemIdDeleteErrors, ThrowOnError>({
        url: '/bank-accounts/{item_id}',
        ...options
    });
};

/**
 * Get Item Route
 */
export const getItemRouteBankAccountsItemIdGet = <ThrowOnError extends boolean = false>(options: Options<GetItemRouteBankAccountsItemIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetItemRouteBankAccountsItemIdGetResponses, GetItemRouteBankAccountsItemIdGetErrors, ThrowOnError>({
        url: '/bank-accounts/{item_id}',
        ...options
    });
};

/**
 * Patch Item Route
 */
export const patchItemRouteBankAccountsItemIdPatch = <ThrowOnError extends boolean = false>(options: Options<PatchItemRouteBankAccountsItemIdPatchData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchItemRouteBankAccountsItemIdPatchResponses, PatchItemRouteBankAccountsItemIdPatchErrors, ThrowOnError>({
        url: '/bank-accounts/{item_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Put Item Route
 */
export const putItemRouteBankAccountsItemIdPut = <ThrowOnError extends boolean = false>(options: Options<PutItemRouteBankAccountsItemIdPutData, ThrowOnError>) => {
    return (options.client ?? client).put<PutItemRouteBankAccountsItemIdPutResponses, PutItemRouteBankAccountsItemIdPutErrors, ThrowOnError>({
        url: '/bank-accounts/{item_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Items Route
 */
export const getItemsRouteLedgerAccountsGet = <ThrowOnError extends boolean = false>(options?: Options<GetItemsRouteLedgerAccountsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetItemsRouteLedgerAccountsGetResponses, GetItemsRouteLedgerAccountsGetErrors, ThrowOnError>({
        url: '/ledger-accounts/',
        ...options
    });
};

/**
 * Post Item Route
 */
export const postItemRouteLedgerAccountsPost = <ThrowOnError extends boolean = false>(options: Options<PostItemRouteLedgerAccountsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<PostItemRouteLedgerAccountsPostResponses, PostItemRouteLedgerAccountsPostErrors, ThrowOnError>({
        url: '/ledger-accounts/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Item Route
 */
export const deleteItemRouteLedgerAccountsItemIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteItemRouteLedgerAccountsItemIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteItemRouteLedgerAccountsItemIdDeleteResponses, DeleteItemRouteLedgerAccountsItemIdDeleteErrors, ThrowOnError>({
        url: '/ledger-accounts/{item_id}',
        ...options
    });
};

/**
 * Get Item Route
 */
export const getItemRouteLedgerAccountsItemIdGet = <ThrowOnError extends boolean = false>(options: Options<GetItemRouteLedgerAccountsItemIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetItemRouteLedgerAccountsItemIdGetResponses, GetItemRouteLedgerAccountsItemIdGetErrors, ThrowOnError>({
        url: '/ledger-accounts/{item_id}',
        ...options
    });
};

/**
 * Patch Item Route
 */
export const patchItemRouteLedgerAccountsItemIdPatch = <ThrowOnError extends boolean = false>(options: Options<PatchItemRouteLedgerAccountsItemIdPatchData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchItemRouteLedgerAccountsItemIdPatchResponses, PatchItemRouteLedgerAccountsItemIdPatchErrors, ThrowOnError>({
        url: '/ledger-accounts/{item_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Put Item Route
 */
export const putItemRouteLedgerAccountsItemIdPut = <ThrowOnError extends boolean = false>(options: Options<PutItemRouteLedgerAccountsItemIdPutData, ThrowOnError>) => {
    return (options.client ?? client).put<PutItemRouteLedgerAccountsItemIdPutResponses, PutItemRouteLedgerAccountsItemIdPutErrors, ThrowOnError>({
        url: '/ledger-accounts/{item_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Related Items Route
 */
export const getRelatedItemsRouteLedgerAccountsItemIdSubAccountsGet = <ThrowOnError extends boolean = false>(options: Options<GetRelatedItemsRouteLedgerAccountsItemIdSubAccountsGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRelatedItemsRouteLedgerAccountsItemIdSubAccountsGetResponses, GetRelatedItemsRouteLedgerAccountsItemIdSubAccountsGetErrors, ThrowOnError>({
        url: '/ledger-accounts/{item_id}/sub-accounts/',
        ...options
    });
};

/**
 * Post Related Item Route
 */
export const postRelatedItemRouteLedgerAccountsItemIdSubAccountsPost = <ThrowOnError extends boolean = false>(options: Options<PostRelatedItemRouteLedgerAccountsItemIdSubAccountsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<PostRelatedItemRouteLedgerAccountsItemIdSubAccountsPostResponses, PostRelatedItemRouteLedgerAccountsItemIdSubAccountsPostErrors, ThrowOnError>({
        url: '/ledger-accounts/{item_id}/sub-accounts/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Related Item Route
 */
export const deleteRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdDeleteResponses, DeleteRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdDeleteErrors, ThrowOnError>({
        url: '/ledger-accounts/{item_id}/sub-accounts/{related_item_id}',
        ...options
    });
};

/**
 * Get Related Item Route
 */
export const getRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdGet = <ThrowOnError extends boolean = false>(options: Options<GetRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdGetResponses, GetRelatedItemRouteLedgerAccountsItemIdSubAccountsRelatedItemIdGetErrors, ThrowOnError>({
        url: '/ledger-accounts/{item_id}/sub-accounts/{related_item_id}',
        ...options
    });
};

/**
 * Get
 */
export const getDummyDaysGet = <ThrowOnError extends boolean = false>(options?: Options<GetDummyDaysGetData, ThrowOnError>) => {
    return (options?.client ?? client).sse.get<GetDummyDaysGetResponses, GetDummyDaysGetErrors, ThrowOnError>({
        url: '/dummy-days/',
        ...options
    });
};
