// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5174' | (string & {});
};

/**
 * BankAccountGet
 */
export type BankAccountGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Asset Account Id
     */
    asset_account_id: string;
    /**
     * Interest Income Account Id
     */
    interest_income_account_id: string;
    /**
     * Interest Receivable Account Id
     */
    interest_receivable_account_id: string;
    /**
     * Fee Expenses Account Id
     */
    fee_expenses_account_id: string;
    /**
     * Fees Payable Account Id
     */
    fees_payable_account_id: string;
    /**
     * Fees Provider Id
     */
    fees_provider_id: string | null;
    /**
     * Fee Payment Schedule Id
     */
    fee_payment_schedule_id: string | null;
    /**
     * Rate Provider Id
     */
    rate_provider_id: string | null;
    /**
     * Interest Payment Schedule Id
     */
    interest_payment_schedule_id: string | null;
};

/**
 * BankAccountPatch
 */
export type BankAccountPatch = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Asset Account Id
     */
    asset_account_id?: string | null;
    /**
     * Interest Income Account Id
     */
    interest_income_account_id?: string | null;
    /**
     * Interest Receivable Account Id
     */
    interest_receivable_account_id?: string | null;
    /**
     * Fee Expenses Account Id
     */
    fee_expenses_account_id?: string | null;
    /**
     * Fees Payable Account Id
     */
    fees_payable_account_id?: string | null;
    /**
     * Fees Provider Id
     */
    fees_provider_id?: string | null;
    /**
     * Fee Payment Schedule Id
     */
    fee_payment_schedule_id?: string | null;
    /**
     * Rate Provider Id
     */
    rate_provider_id?: string | null;
    /**
     * Interest Payment Schedule Id
     */
    interest_payment_schedule_id?: string | null;
};

/**
 * BankAccountPost
 */
export type BankAccountPost = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Asset Account Id
     */
    asset_account_id: string;
    /**
     * Interest Income Account Id
     */
    interest_income_account_id: string;
    /**
     * Interest Receivable Account Id
     */
    interest_receivable_account_id: string;
    /**
     * Fee Expenses Account Id
     */
    fee_expenses_account_id: string;
    /**
     * Fees Payable Account Id
     */
    fees_payable_account_id: string;
    /**
     * Fees Provider Id
     */
    fees_provider_id?: string | null;
    /**
     * Fee Payment Schedule Id
     */
    fee_payment_schedule_id?: string | null;
    /**
     * Rate Provider Id
     */
    rate_provider_id?: string | null;
    /**
     * Interest Payment Schedule Id
     */
    interest_payment_schedule_id?: string | null;
};

/**
 * ChangeTypeError
 */
export type ChangeTypeError = {
    /**
     * Type
     */
    type?: 'change-type';
    /**
     * Current Type
     */
    current_type: string;
    /**
     * New Type
     */
    new_type: string;
};

/**
 * CorporationEntityGet
 */
export type CorporationEntityGet = {
    /**
     * Type
     */
    type: 'corporation_entity';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * CorporationEntityPatch
 */
export type CorporationEntityPatch = {
    /**
     * Type
     */
    type: 'corporation_entity';
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CorporationEntityPost
 */
export type CorporationEntityPost = {
    /**
     * Type
     */
    type: 'corporation_entity';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * DatabaseIntegrityError
 */
export type DatabaseIntegrityError = {
    /**
     * Type
     */
    type?: 'database-integrity';
    /**
     * Message
     */
    message: string;
};

/**
 * DummyDayAccount
 */
export type DummyDayAccount = {
    /**
     * Name
     */
    name: string;
    /**
     * Sub Accounts
     */
    sub_accounts: Array<DummyDayAccount>;
    /**
     * Balance
     */
    balance: number | string;
    /**
     * Total Balance
     */
    total_balance: number | string;
};

/**
 * DummyDayDay
 */
export type DummyDayDay = {
    /**
     * Date
     */
    date: string;
    /**
     * Entities
     */
    entities: Array<DummyDayEntity>;
};

/**
 * DummyDayDayEvent
 */
export type DummyDayDayEvent = {
    /**
     * Type
     */
    type?: 'day';
    /**
     * Idx
     */
    idx: number;
    day: DummyDayDay;
};

/**
 * DummyDayEndEvent
 */
export type DummyDayEndEvent = {
    /**
     * Type
     */
    type?: 'end';
};

/**
 * DummyDayEntity
 */
export type DummyDayEntity = {
    /**
     * Name
     */
    name: string;
    ledger: DummyDayAccount;
};

/**
 * DummyDayError
 */
export type DummyDayError = {
    /**
     * Status Code
     */
    status_code: number;
    /**
     * Message
     */
    message: string;
};

/**
 * DummyDayErrorEvent
 */
export type DummyDayErrorEvent = {
    /**
     * Type
     */
    type?: 'error';
    error: DummyDayError;
};

/**
 * DummyDayEvent
 */
export type DummyDayEvent = ({
    type: 'day';
} & DummyDayDayEvent) | ({
    type: 'end';
} & DummyDayEndEvent) | ({
    type: 'error';
} & DummyDayErrorEvent);

/**
 * EntityScenarioGet
 */
export type EntityScenarioGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * HTTPChangeTypeError
 */
export type HttpChangeTypeError = {
    detail: ChangeTypeError;
};

/**
 * HTTPDatabaseIntegrityError
 */
export type HttpDatabaseIntegrityError = {
    detail: DatabaseIntegrityError;
};

/**
 * HTTPNotFoundError
 */
export type HttpNotFoundError = {
    detail: NotFoundError;
};

/**
 * HTTPRelatedItemNotFoundError
 */
export type HttpRelatedItemNotFoundError = {
    detail: RelatedItemNotFoundError;
};

/**
 * HTTPRelationInvalidError
 */
export type HttpRelationInvalidError = {
    detail: RelationInvalidError;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IndividualEntityGet
 */
export type IndividualEntityGet = {
    /**
     * Type
     */
    type: 'individual_entity';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * IndividualEntityPatch
 */
export type IndividualEntityPatch = {
    /**
     * Type
     */
    type: 'individual_entity';
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * IndividualEntityPost
 */
export type IndividualEntityPost = {
    /**
     * Type
     */
    type: 'individual_entity';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * LedgerAccountGet
 */
export type LedgerAccountGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Account Name
     */
    account_name: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Sub Accounts
     */
    sub_accounts: Array<LedgerAccountGet>;
    parent: LedgerAccountGet | null;
};

/**
 * LedgerAccountPatch
 */
export type LedgerAccountPatch = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Account Name
     */
    account_name?: string | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * LedgerAccountPost
 */
export type LedgerAccountPost = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Account Name
     */
    account_name: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * NotFoundError
 */
export type NotFoundError = {
    /**
     * Type
     */
    type?: 'not-found';
    /**
     * Id
     */
    id: string;
};

/**
 * RelatedItemNotFoundError
 */
export type RelatedItemNotFoundError = {
    /**
     * Type
     */
    type?: 'related-item-not-found';
    /**
     * Relation Name
     */
    relation_name: string;
    /**
     * Id
     */
    id: string;
};

/**
 * RelatedPost
 */
export type RelatedPost = {
    /**
     * Id
     */
    id: string;
};

/**
 * RelationInvalidError
 */
export type RelationInvalidError = {
    /**
     * Type
     */
    type?: 'relation-invalid';
    /**
     * Relation Name
     */
    relation_name: string;
    /**
     * Id
     */
    id: string;
};

/**
 * ScenarioEntityGet
 */
export type ScenarioEntityGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: 'individual_entity' | 'corporation_entity';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * ScenarioGet
 */
export type ScenarioGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * ScenarioPatch
 */
export type ScenarioPatch = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ScenarioPost
 */
export type ScenarioPost = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetItemsRouteScenariosGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/scenarios/';
};

export type GetItemsRouteScenariosGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemsRouteScenariosGetError = GetItemsRouteScenariosGetErrors[keyof GetItemsRouteScenariosGetErrors];

export type GetItemsRouteScenariosGetResponses = {
    /**
     * Response Get Items Route Scenarios  Get
     * Successful Response
     */
    200: Array<ScenarioGet>;
};

export type GetItemsRouteScenariosGetResponse = GetItemsRouteScenariosGetResponses[keyof GetItemsRouteScenariosGetResponses];

export type PostItemRouteScenariosPostData = {
    body: ScenarioPost;
    path?: never;
    query?: never;
    url: '/scenarios/';
};

export type PostItemRouteScenariosPostErrors = {
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteScenariosPostError = PostItemRouteScenariosPostErrors[keyof PostItemRouteScenariosPostErrors];

export type PostItemRouteScenariosPostResponses = {
    /**
     * Successful Response
     */
    201: ScenarioGet;
};

export type PostItemRouteScenariosPostResponse = PostItemRouteScenariosPostResponses[keyof PostItemRouteScenariosPostResponses];

export type DeleteItemRouteScenariosItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}';
};

export type DeleteItemRouteScenariosItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteScenariosItemIdDeleteError = DeleteItemRouteScenariosItemIdDeleteErrors[keyof DeleteItemRouteScenariosItemIdDeleteErrors];

export type DeleteItemRouteScenariosItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGet;
};

export type DeleteItemRouteScenariosItemIdDeleteResponse = DeleteItemRouteScenariosItemIdDeleteResponses[keyof DeleteItemRouteScenariosItemIdDeleteResponses];

export type GetItemRouteScenariosItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/scenarios/{item_id}';
};

export type GetItemRouteScenariosItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteScenariosItemIdGetError = GetItemRouteScenariosItemIdGetErrors[keyof GetItemRouteScenariosItemIdGetErrors];

export type GetItemRouteScenariosItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGet;
};

export type GetItemRouteScenariosItemIdGetResponse = GetItemRouteScenariosItemIdGetResponses[keyof GetItemRouteScenariosItemIdGetResponses];

export type PatchItemRouteScenariosItemIdPatchData = {
    body: ScenarioPatch;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}';
};

export type PatchItemRouteScenariosItemIdPatchErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchItemRouteScenariosItemIdPatchError = PatchItemRouteScenariosItemIdPatchErrors[keyof PatchItemRouteScenariosItemIdPatchErrors];

export type PatchItemRouteScenariosItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGet;
};

export type PatchItemRouteScenariosItemIdPatchResponse = PatchItemRouteScenariosItemIdPatchResponses[keyof PatchItemRouteScenariosItemIdPatchResponses];

export type PutItemRouteScenariosItemIdPutData = {
    body: ScenarioPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}';
};

export type PutItemRouteScenariosItemIdPutErrors = {
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteScenariosItemIdPutError = PutItemRouteScenariosItemIdPutErrors[keyof PutItemRouteScenariosItemIdPutErrors];

export type PutItemRouteScenariosItemIdPutResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGet;
};

export type PutItemRouteScenariosItemIdPutResponse = PutItemRouteScenariosItemIdPutResponses[keyof PutItemRouteScenariosItemIdPutResponses];

export type GetRelatedItemsRouteScenariosItemIdEntitiesGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/scenarios/{item_id}/entities/';
};

export type GetRelatedItemsRouteScenariosItemIdEntitiesGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRelatedItemsRouteScenariosItemIdEntitiesGetError = GetRelatedItemsRouteScenariosItemIdEntitiesGetErrors[keyof GetRelatedItemsRouteScenariosItemIdEntitiesGetErrors];

export type GetRelatedItemsRouteScenariosItemIdEntitiesGetResponses = {
    /**
     * Response Get Related Items Route Scenarios  Item Id  Entities  Get
     * Successful Response
     */
    200: Array<ScenarioEntityGet>;
};

export type GetRelatedItemsRouteScenariosItemIdEntitiesGetResponse = GetRelatedItemsRouteScenariosItemIdEntitiesGetResponses[keyof GetRelatedItemsRouteScenariosItemIdEntitiesGetResponses];

export type PostRelatedItemRouteScenariosItemIdEntitiesPostData = {
    body: RelatedPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}/entities/';
};

export type PostRelatedItemRouteScenariosItemIdEntitiesPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRelatedItemRouteScenariosItemIdEntitiesPostError = PostRelatedItemRouteScenariosItemIdEntitiesPostErrors[keyof PostRelatedItemRouteScenariosItemIdEntitiesPostErrors];

export type PostRelatedItemRouteScenariosItemIdEntitiesPostResponses = {
    /**
     * Successful Response
     */
    201: ScenarioEntityGet;
};

export type PostRelatedItemRouteScenariosItemIdEntitiesPostResponse = PostRelatedItemRouteScenariosItemIdEntitiesPostResponses[keyof PostRelatedItemRouteScenariosItemIdEntitiesPostResponses];

export type DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
        /**
         * Related Item Id
         */
        related_item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}/entities/{related_item_id}';
};

export type DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteErrors = {
    /**
     * Response 404 Delete Related Item Route Scenarios  Item Id  Entities  Related Item Id  Delete
     * Not found
     */
    404: HttpNotFoundError | HttpRelatedItemNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteError = DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteErrors[keyof DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteErrors];

export type DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ScenarioEntityGet;
};

export type DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteResponse = DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteResponses[keyof DeleteRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdDeleteResponses];

export type GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
        /**
         * Related Item Id
         */
        related_item_id: string;
    };
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/scenarios/{item_id}/entities/{related_item_id}';
};

export type GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetErrors = {
    /**
     * Response 404 Get Related Item Route Scenarios  Item Id  Entities  Related Item Id  Get
     * Not found
     */
    404: HttpNotFoundError | HttpRelatedItemNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetError = GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetErrors[keyof GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetErrors];

export type GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ScenarioEntityGet;
};

export type GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetResponse = GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetResponses[keyof GetRelatedItemRouteScenariosItemIdEntitiesRelatedItemIdGetResponses];

export type GetItemsRouteEntitiesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/entities/';
};

export type GetItemsRouteEntitiesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemsRouteEntitiesGetError = GetItemsRouteEntitiesGetErrors[keyof GetItemsRouteEntitiesGetErrors];

export type GetItemsRouteEntitiesGetResponses = {
    /**
     * Response Get Items Route Entities  Get
     * Successful Response
     */
    200: Array<IndividualEntityGet | CorporationEntityGet>;
};

export type GetItemsRouteEntitiesGetResponse = GetItemsRouteEntitiesGetResponses[keyof GetItemsRouteEntitiesGetResponses];

export type PostItemRouteEntitiesPostData = {
    /**
     * Item Post
     */
    body: IndividualEntityPost | CorporationEntityPost;
    path?: never;
    query?: never;
    url: '/entities/';
};

export type PostItemRouteEntitiesPostErrors = {
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteEntitiesPostError = PostItemRouteEntitiesPostErrors[keyof PostItemRouteEntitiesPostErrors];

export type PostItemRouteEntitiesPostResponses = {
    /**
     * Response Post Item Route Entities  Post
     * Successful Response
     */
    201: IndividualEntityGet | CorporationEntityGet;
};

export type PostItemRouteEntitiesPostResponse = PostItemRouteEntitiesPostResponses[keyof PostItemRouteEntitiesPostResponses];

export type DeleteItemRouteEntitiesItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}';
};

export type DeleteItemRouteEntitiesItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteEntitiesItemIdDeleteError = DeleteItemRouteEntitiesItemIdDeleteErrors[keyof DeleteItemRouteEntitiesItemIdDeleteErrors];

export type DeleteItemRouteEntitiesItemIdDeleteResponses = {
    /**
     * Response Delete Item Route Entities  Item Id  Delete
     * Successful Response
     */
    200: IndividualEntityGet | CorporationEntityGet;
};

export type DeleteItemRouteEntitiesItemIdDeleteResponse = DeleteItemRouteEntitiesItemIdDeleteResponses[keyof DeleteItemRouteEntitiesItemIdDeleteResponses];

export type GetItemRouteEntitiesItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/entities/{item_id}';
};

export type GetItemRouteEntitiesItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteEntitiesItemIdGetError = GetItemRouteEntitiesItemIdGetErrors[keyof GetItemRouteEntitiesItemIdGetErrors];

export type GetItemRouteEntitiesItemIdGetResponses = {
    /**
     * Response Get Item Route Entities  Item Id  Get
     * Successful Response
     */
    200: IndividualEntityGet | CorporationEntityGet;
};

export type GetItemRouteEntitiesItemIdGetResponse = GetItemRouteEntitiesItemIdGetResponses[keyof GetItemRouteEntitiesItemIdGetResponses];

export type PatchItemRouteEntitiesItemIdPatchData = {
    /**
     * Item Patch
     */
    body: IndividualEntityPatch | CorporationEntityPatch;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}';
};

export type PatchItemRouteEntitiesItemIdPatchErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Response 409 Patch Item Route Entities  Item Id  Patch
     * Database error
     */
    409: HttpDatabaseIntegrityError | HttpChangeTypeError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchItemRouteEntitiesItemIdPatchError = PatchItemRouteEntitiesItemIdPatchErrors[keyof PatchItemRouteEntitiesItemIdPatchErrors];

export type PatchItemRouteEntitiesItemIdPatchResponses = {
    /**
     * Response Patch Item Route Entities  Item Id  Patch
     * Successful Response
     */
    200: IndividualEntityGet | CorporationEntityGet;
};

export type PatchItemRouteEntitiesItemIdPatchResponse = PatchItemRouteEntitiesItemIdPatchResponses[keyof PatchItemRouteEntitiesItemIdPatchResponses];

export type PutItemRouteEntitiesItemIdPutData = {
    /**
     * Item Post
     */
    body: IndividualEntityPost | CorporationEntityPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}';
};

export type PutItemRouteEntitiesItemIdPutErrors = {
    /**
     * Response 409 Put Item Route Entities  Item Id  Put
     * Database error
     */
    409: HttpDatabaseIntegrityError | HttpChangeTypeError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteEntitiesItemIdPutError = PutItemRouteEntitiesItemIdPutErrors[keyof PutItemRouteEntitiesItemIdPutErrors];

export type PutItemRouteEntitiesItemIdPutResponses = {
    /**
     * Response Put Item Route Entities  Item Id  Put
     * Successful Response
     */
    200: IndividualEntityGet | CorporationEntityGet;
};

export type PutItemRouteEntitiesItemIdPutResponse = PutItemRouteEntitiesItemIdPutResponses[keyof PutItemRouteEntitiesItemIdPutResponses];

export type GetRelatedItemsRouteEntitiesItemIdScenariosGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/entities/{item_id}/scenarios/';
};

export type GetRelatedItemsRouteEntitiesItemIdScenariosGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRelatedItemsRouteEntitiesItemIdScenariosGetError = GetRelatedItemsRouteEntitiesItemIdScenariosGetErrors[keyof GetRelatedItemsRouteEntitiesItemIdScenariosGetErrors];

export type GetRelatedItemsRouteEntitiesItemIdScenariosGetResponses = {
    /**
     * Response Get Related Items Route Entities  Item Id  Scenarios  Get
     * Successful Response
     */
    200: Array<EntityScenarioGet>;
};

export type GetRelatedItemsRouteEntitiesItemIdScenariosGetResponse = GetRelatedItemsRouteEntitiesItemIdScenariosGetResponses[keyof GetRelatedItemsRouteEntitiesItemIdScenariosGetResponses];

export type PostRelatedItemRouteEntitiesItemIdScenariosPostData = {
    body: RelatedPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}/scenarios/';
};

export type PostRelatedItemRouteEntitiesItemIdScenariosPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRelatedItemRouteEntitiesItemIdScenariosPostError = PostRelatedItemRouteEntitiesItemIdScenariosPostErrors[keyof PostRelatedItemRouteEntitiesItemIdScenariosPostErrors];

export type PostRelatedItemRouteEntitiesItemIdScenariosPostResponses = {
    /**
     * Successful Response
     */
    201: EntityScenarioGet;
};

export type PostRelatedItemRouteEntitiesItemIdScenariosPostResponse = PostRelatedItemRouteEntitiesItemIdScenariosPostResponses[keyof PostRelatedItemRouteEntitiesItemIdScenariosPostResponses];

export type DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
        /**
         * Related Item Id
         */
        related_item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}/scenarios/{related_item_id}';
};

export type DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteErrors = {
    /**
     * Response 404 Delete Related Item Route Entities  Item Id  Scenarios  Related Item Id  Delete
     * Not found
     */
    404: HttpNotFoundError | HttpRelatedItemNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteError = DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteErrors[keyof DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteErrors];

export type DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: EntityScenarioGet;
};

export type DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteResponse = DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteResponses[keyof DeleteRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdDeleteResponses];

export type GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
        /**
         * Related Item Id
         */
        related_item_id: string;
    };
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/entities/{item_id}/scenarios/{related_item_id}';
};

export type GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetErrors = {
    /**
     * Response 404 Get Related Item Route Entities  Item Id  Scenarios  Related Item Id  Get
     * Not found
     */
    404: HttpNotFoundError | HttpRelatedItemNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetError = GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetErrors[keyof GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetErrors];

export type GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: EntityScenarioGet;
};

export type GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetResponse = GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetResponses[keyof GetRelatedItemRouteEntitiesItemIdScenariosRelatedItemIdGetResponses];

export type GetItemsRouteBankAccountsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/bank-accounts/';
};

export type GetItemsRouteBankAccountsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemsRouteBankAccountsGetError = GetItemsRouteBankAccountsGetErrors[keyof GetItemsRouteBankAccountsGetErrors];

export type GetItemsRouteBankAccountsGetResponses = {
    /**
     * Response Get Items Route Bank Accounts  Get
     * Successful Response
     */
    200: Array<BankAccountGet>;
};

export type GetItemsRouteBankAccountsGetResponse = GetItemsRouteBankAccountsGetResponses[keyof GetItemsRouteBankAccountsGetResponses];

export type PostItemRouteBankAccountsPostData = {
    body: BankAccountPost;
    path?: never;
    query?: never;
    url: '/bank-accounts/';
};

export type PostItemRouteBankAccountsPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteBankAccountsPostError = PostItemRouteBankAccountsPostErrors[keyof PostItemRouteBankAccountsPostErrors];

export type PostItemRouteBankAccountsPostResponses = {
    /**
     * Successful Response
     */
    201: BankAccountGet;
};

export type PostItemRouteBankAccountsPostResponse = PostItemRouteBankAccountsPostResponses[keyof PostItemRouteBankAccountsPostResponses];

export type DeleteItemRouteBankAccountsItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/bank-accounts/{item_id}';
};

export type DeleteItemRouteBankAccountsItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteBankAccountsItemIdDeleteError = DeleteItemRouteBankAccountsItemIdDeleteErrors[keyof DeleteItemRouteBankAccountsItemIdDeleteErrors];

export type DeleteItemRouteBankAccountsItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: BankAccountGet;
};

export type DeleteItemRouteBankAccountsItemIdDeleteResponse = DeleteItemRouteBankAccountsItemIdDeleteResponses[keyof DeleteItemRouteBankAccountsItemIdDeleteResponses];

export type GetItemRouteBankAccountsItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/bank-accounts/{item_id}';
};

export type GetItemRouteBankAccountsItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteBankAccountsItemIdGetError = GetItemRouteBankAccountsItemIdGetErrors[keyof GetItemRouteBankAccountsItemIdGetErrors];

export type GetItemRouteBankAccountsItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: BankAccountGet;
};

export type GetItemRouteBankAccountsItemIdGetResponse = GetItemRouteBankAccountsItemIdGetResponses[keyof GetItemRouteBankAccountsItemIdGetResponses];

export type PatchItemRouteBankAccountsItemIdPatchData = {
    body: BankAccountPatch;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/bank-accounts/{item_id}';
};

export type PatchItemRouteBankAccountsItemIdPatchErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchItemRouteBankAccountsItemIdPatchError = PatchItemRouteBankAccountsItemIdPatchErrors[keyof PatchItemRouteBankAccountsItemIdPatchErrors];

export type PatchItemRouteBankAccountsItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: BankAccountGet;
};

export type PatchItemRouteBankAccountsItemIdPatchResponse = PatchItemRouteBankAccountsItemIdPatchResponses[keyof PatchItemRouteBankAccountsItemIdPatchResponses];

export type PutItemRouteBankAccountsItemIdPutData = {
    body: BankAccountPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/bank-accounts/{item_id}';
};

export type PutItemRouteBankAccountsItemIdPutErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteBankAccountsItemIdPutError = PutItemRouteBankAccountsItemIdPutErrors[keyof PutItemRouteBankAccountsItemIdPutErrors];

export type PutItemRouteBankAccountsItemIdPutResponses = {
    /**
     * Successful Response
     */
    200: BankAccountGet;
};

export type PutItemRouteBankAccountsItemIdPutResponse = PutItemRouteBankAccountsItemIdPutResponses[keyof PutItemRouteBankAccountsItemIdPutResponses];

export type GetItemsRouteLedgerAccountsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/ledger-accounts/';
};

export type GetItemsRouteLedgerAccountsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemsRouteLedgerAccountsGetError = GetItemsRouteLedgerAccountsGetErrors[keyof GetItemsRouteLedgerAccountsGetErrors];

export type GetItemsRouteLedgerAccountsGetResponses = {
    /**
     * Response Get Items Route Ledger Accounts  Get
     * Successful Response
     */
    200: Array<LedgerAccountGet>;
};

export type GetItemsRouteLedgerAccountsGetResponse = GetItemsRouteLedgerAccountsGetResponses[keyof GetItemsRouteLedgerAccountsGetResponses];

export type PostItemRouteLedgerAccountsPostData = {
    body: LedgerAccountPost;
    path?: never;
    query?: never;
    url: '/ledger-accounts/';
};

export type PostItemRouteLedgerAccountsPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteLedgerAccountsPostError = PostItemRouteLedgerAccountsPostErrors[keyof PostItemRouteLedgerAccountsPostErrors];

export type PostItemRouteLedgerAccountsPostResponses = {
    /**
     * Successful Response
     */
    201: LedgerAccountGet;
};

export type PostItemRouteLedgerAccountsPostResponse = PostItemRouteLedgerAccountsPostResponses[keyof PostItemRouteLedgerAccountsPostResponses];

export type DeleteItemRouteLedgerAccountsItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/ledger-accounts/{item_id}';
};

export type DeleteItemRouteLedgerAccountsItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteLedgerAccountsItemIdDeleteError = DeleteItemRouteLedgerAccountsItemIdDeleteErrors[keyof DeleteItemRouteLedgerAccountsItemIdDeleteErrors];

export type DeleteItemRouteLedgerAccountsItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: LedgerAccountGet;
};

export type DeleteItemRouteLedgerAccountsItemIdDeleteResponse = DeleteItemRouteLedgerAccountsItemIdDeleteResponses[keyof DeleteItemRouteLedgerAccountsItemIdDeleteResponses];

export type GetItemRouteLedgerAccountsItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: {
        /**
         * Depth
         */
        depth?: number;
        /**
         * Max Parents
         */
        max_parents?: number;
    };
    url: '/ledger-accounts/{item_id}';
};

export type GetItemRouteLedgerAccountsItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteLedgerAccountsItemIdGetError = GetItemRouteLedgerAccountsItemIdGetErrors[keyof GetItemRouteLedgerAccountsItemIdGetErrors];

export type GetItemRouteLedgerAccountsItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: LedgerAccountGet;
};

export type GetItemRouteLedgerAccountsItemIdGetResponse = GetItemRouteLedgerAccountsItemIdGetResponses[keyof GetItemRouteLedgerAccountsItemIdGetResponses];

export type PatchItemRouteLedgerAccountsItemIdPatchData = {
    body: LedgerAccountPatch;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/ledger-accounts/{item_id}';
};

export type PatchItemRouteLedgerAccountsItemIdPatchErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchItemRouteLedgerAccountsItemIdPatchError = PatchItemRouteLedgerAccountsItemIdPatchErrors[keyof PatchItemRouteLedgerAccountsItemIdPatchErrors];

export type PatchItemRouteLedgerAccountsItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: LedgerAccountGet;
};

export type PatchItemRouteLedgerAccountsItemIdPatchResponse = PatchItemRouteLedgerAccountsItemIdPatchResponses[keyof PatchItemRouteLedgerAccountsItemIdPatchResponses];

export type PutItemRouteLedgerAccountsItemIdPutData = {
    body: LedgerAccountPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/ledger-accounts/{item_id}';
};

export type PutItemRouteLedgerAccountsItemIdPutErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteLedgerAccountsItemIdPutError = PutItemRouteLedgerAccountsItemIdPutErrors[keyof PutItemRouteLedgerAccountsItemIdPutErrors];

export type PutItemRouteLedgerAccountsItemIdPutResponses = {
    /**
     * Successful Response
     */
    200: LedgerAccountGet;
};

export type PutItemRouteLedgerAccountsItemIdPutResponse = PutItemRouteLedgerAccountsItemIdPutResponses[keyof PutItemRouteLedgerAccountsItemIdPutResponses];

export type GetDummyDaysGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start
         */
        start?: number;
        /**
         * End
         */
        end?: number;
    };
    url: '/dummy-days/';
};

export type GetDummyDaysGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDummyDaysGetError = GetDummyDaysGetErrors[keyof GetDummyDaysGetErrors];

export type GetDummyDaysGetResponses = {
    /**
     * Successful Response
     */
    200: DummyDayEvent;
};

export type GetDummyDaysGetResponse = GetDummyDaysGetResponses[keyof GetDummyDaysGetResponses];
