// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5174' | (string & {});
};

/**
 * AllScheduleGet
 */
export type AllScheduleGet = {
    /**
     * Type
     */
    type: 'all_schedule';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ScheduleScheduledProviderGet>;
    /**
     * All Schedules
     */
    all_schedules: Array<ScheduleAllScheduleGet>;
    /**
     * Any Schedules
     */
    any_schedules: Array<ScheduleAnyScheduleGet>;
    /**
     * Schedules
     */
    schedules: Array<AllScheduleScheduleGet>;
};

/**
 * AllSchedulePost
 */
export type AllSchedulePost = {
    /**
     * Type
     */
    type: 'all_schedule';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Schedules
     */
    schedules: Array<AssociationReference>;
};

/**
 * AllScheduleScheduleGet
 */
export type AllScheduleScheduleGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * AlwaysProviderGet
 */
export type AlwaysProviderGet = {
    /**
     * Type
     */
    type: 'always_provider';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Merge Providers
     */
    merge_providers: Array<ProviderMergeProviderGet>;
    /**
     * Next Providers
     */
    next_providers: Array<ProviderNextProviderGet>;
    /**
     * Value Id
     */
    value_id: string | null;
    value: AlwaysProviderValueGet | null;
};

/**
 * AlwaysProviderPost
 */
export type AlwaysProviderPost = {
    /**
     * Type
     */
    type: 'always_provider';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Value Id
     */
    value_id?: string | null;
};

/**
 * AlwaysProviderValueGet
 */
export type AlwaysProviderValueGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * AnyScheduleGet
 */
export type AnyScheduleGet = {
    /**
     * Type
     */
    type: 'any_schedule';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ScheduleScheduledProviderGet>;
    /**
     * All Schedules
     */
    all_schedules: Array<ScheduleAllScheduleGet>;
    /**
     * Any Schedules
     */
    any_schedules: Array<ScheduleAnyScheduleGet>;
    /**
     * Schedules
     */
    schedules: Array<AnyScheduleScheduleGet>;
};

/**
 * AnySchedulePost
 */
export type AnySchedulePost = {
    /**
     * Type
     */
    type: 'any_schedule';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Schedules
     */
    schedules: Array<AssociationReference>;
};

/**
 * AnyScheduleScheduleGet
 */
export type AnyScheduleScheduleGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * AssociationReference
 */
export type AssociationReference = {
    /**
     * Id
     */
    id: string;
};

/**
 * BandedRateBandGet
 */
export type BandedRateBandGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Size
     */
    size: number | string | null;
    /**
     * Rate Id
     */
    rate_id: string | null;
};

/**
 * BandedRateBandPost
 */
export type BandedRateBandPost = {
    /**
     * Size
     */
    size?: number | string | null;
    /**
     * Rate Id
     */
    rate_id?: string | null;
};

/**
 * BandedRateGet
 */
export type BandedRateGet = {
    /**
     * Type
     */
    type: 'banded_rate';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Banded Rate Bands
     */
    banded_rate_bands: Array<RateBandedRateBandGet>;
    /**
     * Rate Values
     */
    rate_values: Array<FinancialSimulatorAppServerRoutersRatesRateRateValueGet>;
    /**
     * Bands
     */
    bands: Array<BandedRateBandGet>;
};

/**
 * BandedRatePost
 */
export type BandedRatePost = {
    /**
     * Type
     */
    type: 'banded_rate';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Bands
     */
    bands: Array<BandedRateBandPost>;
};

/**
 * BankAccountGet
 */
export type BankAccountGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Asset Account Id
     */
    asset_account_id: string | null;
    /**
     * Interest Income Account Id
     */
    interest_income_account_id: string | null;
    /**
     * Interest Receivable Account Id
     */
    interest_receivable_account_id: string | null;
    /**
     * Fee Expenses Account Id
     */
    fee_expenses_account_id: string | null;
    /**
     * Fees Payable Account Id
     */
    fees_payable_account_id: string | null;
    /**
     * Fees Provider Id
     */
    fees_provider_id: string | null;
    /**
     * Fee Payment Schedule Id
     */
    fee_payment_schedule_id: string | null;
    /**
     * Rate Provider Id
     */
    rate_provider_id: string | null;
    /**
     * Interest Payment Schedule Id
     */
    interest_payment_schedule_id: string | null;
};

/**
 * BankAccountPost
 */
export type BankAccountPost = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Asset Account Id
     */
    asset_account_id?: string | null;
    /**
     * Interest Income Account Id
     */
    interest_income_account_id?: string | null;
    /**
     * Interest Receivable Account Id
     */
    interest_receivable_account_id?: string | null;
    /**
     * Fee Expenses Account Id
     */
    fee_expenses_account_id?: string | null;
    /**
     * Fees Payable Account Id
     */
    fees_payable_account_id?: string | null;
    /**
     * Fees Provider Id
     */
    fees_provider_id?: string | null;
    /**
     * Fee Payment Schedule Id
     */
    fee_payment_schedule_id?: string | null;
    /**
     * Rate Provider Id
     */
    rate_provider_id?: string | null;
    /**
     * Interest Payment Schedule Id
     */
    interest_payment_schedule_id?: string | null;
};

/**
 * ChangeTypeError
 */
export type ChangeTypeError = {
    /**
     * Type
     */
    type?: 'change-type';
    /**
     * Current Type
     */
    current_type: string;
    /**
     * New Type
     */
    new_type: string;
};

/**
 * ContinuousRateGet
 */
export type ContinuousRateGet = {
    /**
     * Type
     */
    type: 'continuous_rate';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Banded Rate Bands
     */
    banded_rate_bands: Array<RateBandedRateBandGet>;
    /**
     * Rate Values
     */
    rate_values: Array<FinancialSimulatorAppServerRoutersRatesRateRateValueGet>;
    /**
     * Annual Rate
     */
    annual_rate: number | string | null;
};

/**
 * ContinuousRatePost
 */
export type ContinuousRatePost = {
    /**
     * Type
     */
    type: 'continuous_rate';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Annual Rate
     */
    annual_rate?: number | string | null;
};

/**
 * CorporationEntityGet
 */
export type CorporationEntityGet = {
    /**
     * Type
     */
    type: 'corporation_entity';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scenarios
     */
    scenarios: Array<EntityScenarioGet>;
};

/**
 * CorporationEntityPost
 */
export type CorporationEntityPost = {
    /**
     * Type
     */
    type: 'corporation_entity';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Scenarios
     */
    scenarios: Array<ManyToManyReference>;
};

/**
 * DailyScheduleGet
 */
export type DailyScheduleGet = {
    /**
     * Type
     */
    type: 'daily_schedule';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ScheduleScheduledProviderGet>;
    /**
     * All Schedules
     */
    all_schedules: Array<ScheduleAllScheduleGet>;
    /**
     * Any Schedules
     */
    any_schedules: Array<ScheduleAnyScheduleGet>;
};

/**
 * DailySchedulePost
 */
export type DailySchedulePost = {
    /**
     * Type
     */
    type: 'daily_schedule';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * DatabaseIntegrityError
 */
export type DatabaseIntegrityError = {
    /**
     * Type
     */
    type?: 'database-integrity';
    /**
     * Message
     */
    message: string;
};

/**
 * DayScheduleGet
 */
export type DayScheduleGet = {
    /**
     * Type
     */
    type: 'day_schedule';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ScheduleScheduledProviderGet>;
    /**
     * All Schedules
     */
    all_schedules: Array<ScheduleAllScheduleGet>;
    /**
     * Any Schedules
     */
    any_schedules: Array<ScheduleAnyScheduleGet>;
    /**
     * Day
     */
    day: string | null;
};

/**
 * DaySchedulePost
 */
export type DaySchedulePost = {
    /**
     * Type
     */
    type: 'day_schedule';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Day
     */
    day?: string | null;
};

/**
 * DecimalValueGet
 */
export type DecimalValueGet = {
    /**
     * Type
     */
    type: 'decimal_value';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Always Providers
     */
    always_providers: Array<ValueAlwaysProviderGet>;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ValueScheduledProviderGet>;
    /**
     * Value
     */
    value: number | string | null;
};

/**
 * DecimalValuePost
 */
export type DecimalValuePost = {
    /**
     * Type
     */
    type: 'decimal_value';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Value
     */
    value?: number | string | null;
};

/**
 * DummyDayAccount
 */
export type DummyDayAccount = {
    /**
     * Name
     */
    name: string;
    /**
     * Sub Accounts
     */
    sub_accounts: Array<DummyDayAccount>;
    /**
     * Balance
     */
    balance: number | string;
    /**
     * Total Balance
     */
    total_balance: number | string;
};

/**
 * DummyDayDay
 */
export type DummyDayDay = {
    /**
     * Date
     */
    date: string;
    /**
     * Entities
     */
    entities: Array<DummyDayEntity>;
};

/**
 * DummyDayDayEvent
 */
export type DummyDayDayEvent = {
    /**
     * Type
     */
    type?: 'day';
    /**
     * Idx
     */
    idx: number;
    day: DummyDayDay;
};

/**
 * DummyDayEndEvent
 */
export type DummyDayEndEvent = {
    /**
     * Type
     */
    type?: 'end';
};

/**
 * DummyDayEntity
 */
export type DummyDayEntity = {
    /**
     * Name
     */
    name: string;
    ledger: DummyDayAccount;
};

/**
 * DummyDayError
 */
export type DummyDayError = {
    /**
     * Status Code
     */
    status_code: number;
    /**
     * Message
     */
    message: string;
};

/**
 * DummyDayErrorEvent
 */
export type DummyDayErrorEvent = {
    /**
     * Type
     */
    type?: 'error';
    error: DummyDayError;
};

/**
 * DummyDayEvent
 */
export type DummyDayEvent = ({
    type: 'day';
} & DummyDayDayEvent) | ({
    type: 'end';
} & DummyDayEndEvent) | ({
    type: 'error';
} & DummyDayErrorEvent);

/**
 * EntityScenarioGet
 */
export type EntityScenarioGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * FromScheduleGet
 */
export type FromScheduleGet = {
    /**
     * Type
     */
    type: 'from_schedule';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ScheduleScheduledProviderGet>;
    /**
     * All Schedules
     */
    all_schedules: Array<ScheduleAllScheduleGet>;
    /**
     * Any Schedules
     */
    any_schedules: Array<ScheduleAnyScheduleGet>;
    /**
     * From Date
     */
    from_date: string | null;
};

/**
 * FromSchedulePost
 */
export type FromSchedulePost = {
    /**
     * Type
     */
    type: 'from_schedule';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * From Date
     */
    from_date?: string | null;
};

/**
 * HTTPChangeTypeError
 */
export type HttpChangeTypeError = {
    detail: ChangeTypeError;
};

/**
 * HTTPDatabaseIntegrityError
 */
export type HttpDatabaseIntegrityError = {
    detail: DatabaseIntegrityError;
};

/**
 * HTTPNotFoundError
 */
export type HttpNotFoundError = {
    detail: NotFoundError;
};

/**
 * HTTPRelationInvalidError
 */
export type HttpRelationInvalidError = {
    detail: RelationInvalidError;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IndividualEntityGet
 */
export type IndividualEntityGet = {
    /**
     * Type
     */
    type: 'individual_entity';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scenarios
     */
    scenarios: Array<EntityScenarioGet>;
};

/**
 * IndividualEntityPost
 */
export type IndividualEntityPost = {
    /**
     * Type
     */
    type: 'individual_entity';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Scenarios
     */
    scenarios: Array<ManyToManyReference>;
};

/**
 * LedgerAccountBankAccountGet
 */
export type LedgerAccountBankAccountGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * LedgerAccountGet
 */
export type LedgerAccountGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Account Name
     */
    account_name: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Sub Accounts
     */
    sub_accounts: Array<LedgerAccountGet>;
    parent: LedgerAccountGet | null;
    /**
     * Bank Account Asset Accounts
     */
    bank_account_asset_accounts: Array<LedgerAccountBankAccountGet>;
    /**
     * Bank Account Interest Income Accounts
     */
    bank_account_interest_income_accounts: Array<LedgerAccountBankAccountGet>;
    /**
     * Bank Account Interest Receivable Accounts
     */
    bank_account_interest_receivable_accounts: Array<LedgerAccountBankAccountGet>;
    /**
     * Bank Account Fee Expenses Accounts
     */
    bank_account_fee_expenses_accounts: Array<LedgerAccountBankAccountGet>;
    /**
     * Bank Account Fees Payable Accounts
     */
    bank_account_fees_payable_accounts: Array<LedgerAccountBankAccountGet>;
};

/**
 * LedgerAccountPost
 */
export type LedgerAccountPost = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Account Name
     */
    account_name: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * ManyToManyReference
 */
export type ManyToManyReference = {
    /**
     * Id
     */
    id: string;
};

/**
 * MergeProviderGet
 */
export type MergeProviderGet = {
    /**
     * Type
     */
    type: 'merge_provider';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Merge Providers
     */
    merge_providers: Array<ProviderMergeProviderGet>;
    /**
     * Next Providers
     */
    next_providers: Array<ProviderNextProviderGet>;
    /**
     * Providers
     */
    providers: Array<MergeProviderProviderGet>;
};

/**
 * MergeProviderPost
 */
export type MergeProviderPost = {
    /**
     * Type
     */
    type: 'merge_provider';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Providers
     */
    providers: Array<AssociationReference>;
};

/**
 * MergeProviderProviderGet
 */
export type MergeProviderProviderGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * MonthlyScheduleGet
 */
export type MonthlyScheduleGet = {
    /**
     * Type
     */
    type: 'monthly_schedule';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ScheduleScheduledProviderGet>;
    /**
     * All Schedules
     */
    all_schedules: Array<ScheduleAllScheduleGet>;
    /**
     * Any Schedules
     */
    any_schedules: Array<ScheduleAnyScheduleGet>;
    /**
     * Day
     */
    day: number | null;
};

/**
 * MonthlySchedulePost
 */
export type MonthlySchedulePost = {
    /**
     * Type
     */
    type: 'monthly_schedule';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Day
     */
    day?: number | null;
};

/**
 * NextProviderGet
 */
export type NextProviderGet = {
    /**
     * Type
     */
    type: 'next_provider';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Merge Providers
     */
    merge_providers: Array<ProviderMergeProviderGet>;
    /**
     * Next Providers
     */
    next_providers: Array<ProviderNextProviderGet>;
    /**
     * Providers
     */
    providers: Array<NextProviderProviderGet>;
};

/**
 * NextProviderPost
 */
export type NextProviderPost = {
    /**
     * Type
     */
    type: 'next_provider';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Providers
     */
    providers: Array<AssociationReference>;
};

/**
 * NextProviderProviderGet
 */
export type NextProviderProviderGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * NotFoundError
 */
export type NotFoundError = {
    /**
     * Type
     */
    type?: 'not-found';
    /**
     * Id
     */
    id: string;
};

/**
 * PeriodicRateGet
 */
export type PeriodicRateGet = {
    /**
     * Type
     */
    type: 'periodic_rate';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Banded Rate Bands
     */
    banded_rate_bands: Array<RateBandedRateBandGet>;
    /**
     * Rate Values
     */
    rate_values: Array<FinancialSimulatorAppServerRoutersRatesRateRateValueGet>;
    /**
     * Annual Rate
     */
    annual_rate: number | string | null;
    /**
     * Period Count
     */
    period_count: number | null;
};

/**
 * PeriodicRatePost
 */
export type PeriodicRatePost = {
    /**
     * Type
     */
    type: 'periodic_rate';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Annual Rate
     */
    annual_rate?: number | string | null;
    /**
     * Period Count
     */
    period_count?: number | null;
};

/**
 * ProviderMergeProviderGet
 */
export type ProviderMergeProviderGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * ProviderNextProviderGet
 */
export type ProviderNextProviderGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * RangeScheduleGet
 */
export type RangeScheduleGet = {
    /**
     * Type
     */
    type: 'range_schedule';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ScheduleScheduledProviderGet>;
    /**
     * All Schedules
     */
    all_schedules: Array<ScheduleAllScheduleGet>;
    /**
     * Any Schedules
     */
    any_schedules: Array<ScheduleAnyScheduleGet>;
    /**
     * From Date
     */
    from_date: string | null;
    /**
     * Until Date
     */
    until_date: string | null;
};

/**
 * RangeSchedulePost
 */
export type RangeSchedulePost = {
    /**
     * Type
     */
    type: 'range_schedule';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * From Date
     */
    from_date?: string | null;
    /**
     * Until Date
     */
    until_date?: string | null;
};

/**
 * RateBandedRateBandGet
 */
export type RateBandedRateBandGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Banded Rate Id
     */
    banded_rate_id: string;
    /**
     * Size
     */
    size: number | string | null;
};

/**
 * RateValuePost
 */
export type RateValuePost = {
    /**
     * Type
     */
    type: 'rate_value';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Rate Id
     */
    rate_id?: string | null;
};

/**
 * RateValueRateGet
 */
export type RateValueRateGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * RelationInvalidError
 */
export type RelationInvalidError = {
    /**
     * Type
     */
    type?: 'relation-invalid';
    /**
     * Relation Name
     */
    relation_name: string;
    /**
     * Id
     */
    id: string;
};

/**
 * ScenarioEntityGet
 */
export type ScenarioEntityGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: 'individual_entity' | 'corporation_entity';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * ScenarioGet
 */
export type ScenarioGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Entities
     */
    entities: Array<ScenarioEntityGet>;
};

/**
 * ScenarioPost
 */
export type ScenarioPost = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Entities
     */
    entities: Array<ManyToManyReference>;
};

/**
 * ScheduleAllScheduleGet
 */
export type ScheduleAllScheduleGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * ScheduleAnyScheduleGet
 */
export type ScheduleAnyScheduleGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * ScheduleScheduledProviderGet
 */
export type ScheduleScheduledProviderGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * ScheduledProviderGet
 */
export type ScheduledProviderGet = {
    /**
     * Type
     */
    type: 'scheduled_provider';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Merge Providers
     */
    merge_providers: Array<ProviderMergeProviderGet>;
    /**
     * Next Providers
     */
    next_providers: Array<ProviderNextProviderGet>;
    /**
     * Value Id
     */
    value_id: string | null;
    /**
     * Schedule Id
     */
    schedule_id: string | null;
    value: ScheduledProviderValueGet | null;
    schedule: ScheduledProviderScheduleGet | null;
};

/**
 * ScheduledProviderPost
 */
export type ScheduledProviderPost = {
    /**
     * Type
     */
    type: 'scheduled_provider';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Value Id
     */
    value_id?: string | null;
    /**
     * Schedule Id
     */
    schedule_id?: string | null;
};

/**
 * ScheduledProviderScheduleGet
 */
export type ScheduledProviderScheduleGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * ScheduledProviderValueGet
 */
export type ScheduledProviderValueGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * UntilScheduleGet
 */
export type UntilScheduleGet = {
    /**
     * Type
     */
    type: 'until_schedule';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ScheduleScheduledProviderGet>;
    /**
     * All Schedules
     */
    all_schedules: Array<ScheduleAllScheduleGet>;
    /**
     * Any Schedules
     */
    any_schedules: Array<ScheduleAnyScheduleGet>;
    /**
     * Until Date
     */
    until_date: string | null;
};

/**
 * UntilSchedulePost
 */
export type UntilSchedulePost = {
    /**
     * Type
     */
    type: 'until_schedule';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Until Date
     */
    until_date?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * ValueAlwaysProviderGet
 */
export type ValueAlwaysProviderGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * ValueScheduledProviderGet
 */
export type ValueScheduledProviderGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * WeeklyScheduleGet
 */
export type WeeklyScheduleGet = {
    /**
     * Type
     */
    type: 'weekly_schedule';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ScheduleScheduledProviderGet>;
    /**
     * All Schedules
     */
    all_schedules: Array<ScheduleAllScheduleGet>;
    /**
     * Any Schedules
     */
    any_schedules: Array<ScheduleAnyScheduleGet>;
    /**
     * Weekday
     */
    weekday: number | null;
};

/**
 * WeeklySchedulePost
 */
export type WeeklySchedulePost = {
    /**
     * Type
     */
    type: 'weekly_schedule';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Weekday
     */
    weekday?: number | null;
};

/**
 * YearlyScheduleGet
 */
export type YearlyScheduleGet = {
    /**
     * Type
     */
    type: 'yearly_schedule';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ScheduleScheduledProviderGet>;
    /**
     * All Schedules
     */
    all_schedules: Array<ScheduleAllScheduleGet>;
    /**
     * Any Schedules
     */
    any_schedules: Array<ScheduleAnyScheduleGet>;
    /**
     * Month
     */
    month: number | null;
    /**
     * Day
     */
    day: number | null;
};

/**
 * YearlySchedulePost
 */
export type YearlySchedulePost = {
    /**
     * Type
     */
    type: 'yearly_schedule';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Month
     */
    month?: number | null;
    /**
     * Day
     */
    day?: number | null;
};

/**
 * RateValueGet
 */
export type FinancialSimulatorAppServerRoutersRatesRateRateValueGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * RateValueGet
 */
export type FinancialSimulatorAppServerRoutersValuesRateValueRateValueGet = {
    /**
     * Type
     */
    type: 'rate_value';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Always Providers
     */
    always_providers: Array<ValueAlwaysProviderGet>;
    /**
     * Scheduled Providers
     */
    scheduled_providers: Array<ValueScheduledProviderGet>;
    /**
     * Rate Id
     */
    rate_id: string | null;
    rate: RateValueRateGet | null;
};

export type GetItemsRouteScenariosGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/scenarios/';
};

export type GetItemsRouteScenariosGetResponses = {
    /**
     * Response Get Items Route Scenarios  Get
     * Successful Response
     */
    200: Array<ScenarioGet>;
};

export type GetItemsRouteScenariosGetResponse = GetItemsRouteScenariosGetResponses[keyof GetItemsRouteScenariosGetResponses];

export type PostItemRouteScenariosPostData = {
    body: ScenarioPost;
    path?: never;
    query?: never;
    url: '/scenarios/';
};

export type PostItemRouteScenariosPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteScenariosPostError = PostItemRouteScenariosPostErrors[keyof PostItemRouteScenariosPostErrors];

export type PostItemRouteScenariosPostResponses = {
    /**
     * Successful Response
     */
    201: ScenarioGet;
};

export type PostItemRouteScenariosPostResponse = PostItemRouteScenariosPostResponses[keyof PostItemRouteScenariosPostResponses];

export type DeleteItemRouteScenariosItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}';
};

export type DeleteItemRouteScenariosItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteScenariosItemIdDeleteError = DeleteItemRouteScenariosItemIdDeleteErrors[keyof DeleteItemRouteScenariosItemIdDeleteErrors];

export type DeleteItemRouteScenariosItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGet;
};

export type DeleteItemRouteScenariosItemIdDeleteResponse = DeleteItemRouteScenariosItemIdDeleteResponses[keyof DeleteItemRouteScenariosItemIdDeleteResponses];

export type GetItemRouteScenariosItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}';
};

export type GetItemRouteScenariosItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteScenariosItemIdGetError = GetItemRouteScenariosItemIdGetErrors[keyof GetItemRouteScenariosItemIdGetErrors];

export type GetItemRouteScenariosItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGet;
};

export type GetItemRouteScenariosItemIdGetResponse = GetItemRouteScenariosItemIdGetResponses[keyof GetItemRouteScenariosItemIdGetResponses];

export type PutItemRouteScenariosItemIdPutData = {
    body: ScenarioPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}';
};

export type PutItemRouteScenariosItemIdPutErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteScenariosItemIdPutError = PutItemRouteScenariosItemIdPutErrors[keyof PutItemRouteScenariosItemIdPutErrors];

export type PutItemRouteScenariosItemIdPutResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGet;
};

export type PutItemRouteScenariosItemIdPutResponse = PutItemRouteScenariosItemIdPutResponses[keyof PutItemRouteScenariosItemIdPutResponses];

export type GetItemsRouteEntitiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/entities/';
};

export type GetItemsRouteEntitiesGetResponses = {
    /**
     * Response Get Items Route Entities  Get
     * Successful Response
     */
    200: Array<IndividualEntityGet | CorporationEntityGet>;
};

export type GetItemsRouteEntitiesGetResponse = GetItemsRouteEntitiesGetResponses[keyof GetItemsRouteEntitiesGetResponses];

export type PostItemRouteEntitiesPostData = {
    /**
     * Item Post
     */
    body: IndividualEntityPost | CorporationEntityPost;
    path?: never;
    query?: never;
    url: '/entities/';
};

export type PostItemRouteEntitiesPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteEntitiesPostError = PostItemRouteEntitiesPostErrors[keyof PostItemRouteEntitiesPostErrors];

export type PostItemRouteEntitiesPostResponses = {
    /**
     * Response Post Item Route Entities  Post
     * Successful Response
     */
    201: IndividualEntityGet | CorporationEntityGet;
};

export type PostItemRouteEntitiesPostResponse = PostItemRouteEntitiesPostResponses[keyof PostItemRouteEntitiesPostResponses];

export type DeleteItemRouteEntitiesItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}';
};

export type DeleteItemRouteEntitiesItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteEntitiesItemIdDeleteError = DeleteItemRouteEntitiesItemIdDeleteErrors[keyof DeleteItemRouteEntitiesItemIdDeleteErrors];

export type DeleteItemRouteEntitiesItemIdDeleteResponses = {
    /**
     * Response Delete Item Route Entities  Item Id  Delete
     * Successful Response
     */
    200: IndividualEntityGet | CorporationEntityGet;
};

export type DeleteItemRouteEntitiesItemIdDeleteResponse = DeleteItemRouteEntitiesItemIdDeleteResponses[keyof DeleteItemRouteEntitiesItemIdDeleteResponses];

export type GetItemRouteEntitiesItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}';
};

export type GetItemRouteEntitiesItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteEntitiesItemIdGetError = GetItemRouteEntitiesItemIdGetErrors[keyof GetItemRouteEntitiesItemIdGetErrors];

export type GetItemRouteEntitiesItemIdGetResponses = {
    /**
     * Response Get Item Route Entities  Item Id  Get
     * Successful Response
     */
    200: IndividualEntityGet | CorporationEntityGet;
};

export type GetItemRouteEntitiesItemIdGetResponse = GetItemRouteEntitiesItemIdGetResponses[keyof GetItemRouteEntitiesItemIdGetResponses];

export type PutItemRouteEntitiesItemIdPutData = {
    /**
     * Item Post
     */
    body: IndividualEntityPost | CorporationEntityPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}';
};

export type PutItemRouteEntitiesItemIdPutErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Response 409 Put Item Route Entities  Item Id  Put
     * Database error
     */
    409: HttpDatabaseIntegrityError | HttpChangeTypeError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteEntitiesItemIdPutError = PutItemRouteEntitiesItemIdPutErrors[keyof PutItemRouteEntitiesItemIdPutErrors];

export type PutItemRouteEntitiesItemIdPutResponses = {
    /**
     * Response Put Item Route Entities  Item Id  Put
     * Successful Response
     */
    200: IndividualEntityGet | CorporationEntityGet;
};

export type PutItemRouteEntitiesItemIdPutResponse = PutItemRouteEntitiesItemIdPutResponses[keyof PutItemRouteEntitiesItemIdPutResponses];

export type GetItemsRouteBankAccountsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bank-accounts/';
};

export type GetItemsRouteBankAccountsGetResponses = {
    /**
     * Response Get Items Route Bank Accounts  Get
     * Successful Response
     */
    200: Array<BankAccountGet>;
};

export type GetItemsRouteBankAccountsGetResponse = GetItemsRouteBankAccountsGetResponses[keyof GetItemsRouteBankAccountsGetResponses];

export type PostItemRouteBankAccountsPostData = {
    body: BankAccountPost;
    path?: never;
    query?: never;
    url: '/bank-accounts/';
};

export type PostItemRouteBankAccountsPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteBankAccountsPostError = PostItemRouteBankAccountsPostErrors[keyof PostItemRouteBankAccountsPostErrors];

export type PostItemRouteBankAccountsPostResponses = {
    /**
     * Successful Response
     */
    201: BankAccountGet;
};

export type PostItemRouteBankAccountsPostResponse = PostItemRouteBankAccountsPostResponses[keyof PostItemRouteBankAccountsPostResponses];

export type DeleteItemRouteBankAccountsItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/bank-accounts/{item_id}';
};

export type DeleteItemRouteBankAccountsItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteBankAccountsItemIdDeleteError = DeleteItemRouteBankAccountsItemIdDeleteErrors[keyof DeleteItemRouteBankAccountsItemIdDeleteErrors];

export type DeleteItemRouteBankAccountsItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: BankAccountGet;
};

export type DeleteItemRouteBankAccountsItemIdDeleteResponse = DeleteItemRouteBankAccountsItemIdDeleteResponses[keyof DeleteItemRouteBankAccountsItemIdDeleteResponses];

export type GetItemRouteBankAccountsItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/bank-accounts/{item_id}';
};

export type GetItemRouteBankAccountsItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteBankAccountsItemIdGetError = GetItemRouteBankAccountsItemIdGetErrors[keyof GetItemRouteBankAccountsItemIdGetErrors];

export type GetItemRouteBankAccountsItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: BankAccountGet;
};

export type GetItemRouteBankAccountsItemIdGetResponse = GetItemRouteBankAccountsItemIdGetResponses[keyof GetItemRouteBankAccountsItemIdGetResponses];

export type PutItemRouteBankAccountsItemIdPutData = {
    body: BankAccountPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/bank-accounts/{item_id}';
};

export type PutItemRouteBankAccountsItemIdPutErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteBankAccountsItemIdPutError = PutItemRouteBankAccountsItemIdPutErrors[keyof PutItemRouteBankAccountsItemIdPutErrors];

export type PutItemRouteBankAccountsItemIdPutResponses = {
    /**
     * Successful Response
     */
    200: BankAccountGet;
};

export type PutItemRouteBankAccountsItemIdPutResponse = PutItemRouteBankAccountsItemIdPutResponses[keyof PutItemRouteBankAccountsItemIdPutResponses];

export type GetItemsRouteLedgerAccountsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ledger-accounts/';
};

export type GetItemsRouteLedgerAccountsGetResponses = {
    /**
     * Response Get Items Route Ledger Accounts  Get
     * Successful Response
     */
    200: Array<LedgerAccountGet>;
};

export type GetItemsRouteLedgerAccountsGetResponse = GetItemsRouteLedgerAccountsGetResponses[keyof GetItemsRouteLedgerAccountsGetResponses];

export type PostItemRouteLedgerAccountsPostData = {
    body: LedgerAccountPost;
    path?: never;
    query?: never;
    url: '/ledger-accounts/';
};

export type PostItemRouteLedgerAccountsPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteLedgerAccountsPostError = PostItemRouteLedgerAccountsPostErrors[keyof PostItemRouteLedgerAccountsPostErrors];

export type PostItemRouteLedgerAccountsPostResponses = {
    /**
     * Successful Response
     */
    201: LedgerAccountGet;
};

export type PostItemRouteLedgerAccountsPostResponse = PostItemRouteLedgerAccountsPostResponses[keyof PostItemRouteLedgerAccountsPostResponses];

export type DeleteItemRouteLedgerAccountsItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/ledger-accounts/{item_id}';
};

export type DeleteItemRouteLedgerAccountsItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteLedgerAccountsItemIdDeleteError = DeleteItemRouteLedgerAccountsItemIdDeleteErrors[keyof DeleteItemRouteLedgerAccountsItemIdDeleteErrors];

export type DeleteItemRouteLedgerAccountsItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: LedgerAccountGet;
};

export type DeleteItemRouteLedgerAccountsItemIdDeleteResponse = DeleteItemRouteLedgerAccountsItemIdDeleteResponses[keyof DeleteItemRouteLedgerAccountsItemIdDeleteResponses];

export type GetItemRouteLedgerAccountsItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/ledger-accounts/{item_id}';
};

export type GetItemRouteLedgerAccountsItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteLedgerAccountsItemIdGetError = GetItemRouteLedgerAccountsItemIdGetErrors[keyof GetItemRouteLedgerAccountsItemIdGetErrors];

export type GetItemRouteLedgerAccountsItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: LedgerAccountGet;
};

export type GetItemRouteLedgerAccountsItemIdGetResponse = GetItemRouteLedgerAccountsItemIdGetResponses[keyof GetItemRouteLedgerAccountsItemIdGetResponses];

export type PutItemRouteLedgerAccountsItemIdPutData = {
    body: LedgerAccountPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/ledger-accounts/{item_id}';
};

export type PutItemRouteLedgerAccountsItemIdPutErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteLedgerAccountsItemIdPutError = PutItemRouteLedgerAccountsItemIdPutErrors[keyof PutItemRouteLedgerAccountsItemIdPutErrors];

export type PutItemRouteLedgerAccountsItemIdPutResponses = {
    /**
     * Successful Response
     */
    200: LedgerAccountGet;
};

export type PutItemRouteLedgerAccountsItemIdPutResponse = PutItemRouteLedgerAccountsItemIdPutResponses[keyof PutItemRouteLedgerAccountsItemIdPutResponses];

export type GetItemsRouteRatesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rates/';
};

export type GetItemsRouteRatesGetResponses = {
    /**
     * Response Get Items Route Rates  Get
     * Successful Response
     */
    200: Array<PeriodicRateGet | ContinuousRateGet | BandedRateGet>;
};

export type GetItemsRouteRatesGetResponse = GetItemsRouteRatesGetResponses[keyof GetItemsRouteRatesGetResponses];

export type PostItemRouteRatesPostData = {
    /**
     * Item Post
     */
    body: PeriodicRatePost | ContinuousRatePost | BandedRatePost;
    path?: never;
    query?: never;
    url: '/rates/';
};

export type PostItemRouteRatesPostErrors = {
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteRatesPostError = PostItemRouteRatesPostErrors[keyof PostItemRouteRatesPostErrors];

export type PostItemRouteRatesPostResponses = {
    /**
     * Response Post Item Route Rates  Post
     * Successful Response
     */
    201: PeriodicRateGet | ContinuousRateGet | BandedRateGet;
};

export type PostItemRouteRatesPostResponse = PostItemRouteRatesPostResponses[keyof PostItemRouteRatesPostResponses];

export type DeleteItemRouteRatesItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/rates/{item_id}';
};

export type DeleteItemRouteRatesItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteRatesItemIdDeleteError = DeleteItemRouteRatesItemIdDeleteErrors[keyof DeleteItemRouteRatesItemIdDeleteErrors];

export type DeleteItemRouteRatesItemIdDeleteResponses = {
    /**
     * Response Delete Item Route Rates  Item Id  Delete
     * Successful Response
     */
    200: PeriodicRateGet | ContinuousRateGet | BandedRateGet;
};

export type DeleteItemRouteRatesItemIdDeleteResponse = DeleteItemRouteRatesItemIdDeleteResponses[keyof DeleteItemRouteRatesItemIdDeleteResponses];

export type GetItemRouteRatesItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/rates/{item_id}';
};

export type GetItemRouteRatesItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteRatesItemIdGetError = GetItemRouteRatesItemIdGetErrors[keyof GetItemRouteRatesItemIdGetErrors];

export type GetItemRouteRatesItemIdGetResponses = {
    /**
     * Response Get Item Route Rates  Item Id  Get
     * Successful Response
     */
    200: PeriodicRateGet | ContinuousRateGet | BandedRateGet;
};

export type GetItemRouteRatesItemIdGetResponse = GetItemRouteRatesItemIdGetResponses[keyof GetItemRouteRatesItemIdGetResponses];

export type PutItemRouteRatesItemIdPutData = {
    /**
     * Item Post
     */
    body: PeriodicRatePost | ContinuousRatePost | BandedRatePost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/rates/{item_id}';
};

export type PutItemRouteRatesItemIdPutErrors = {
    /**
     * Response 409 Put Item Route Rates  Item Id  Put
     * Database error
     */
    409: HttpDatabaseIntegrityError | HttpChangeTypeError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteRatesItemIdPutError = PutItemRouteRatesItemIdPutErrors[keyof PutItemRouteRatesItemIdPutErrors];

export type PutItemRouteRatesItemIdPutResponses = {
    /**
     * Response Put Item Route Rates  Item Id  Put
     * Successful Response
     */
    200: PeriodicRateGet | ContinuousRateGet | BandedRateGet;
};

export type PutItemRouteRatesItemIdPutResponse = PutItemRouteRatesItemIdPutResponses[keyof PutItemRouteRatesItemIdPutResponses];

export type GetItemsRouteValuesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/values/';
};

export type GetItemsRouteValuesGetResponses = {
    /**
     * Response Get Items Route Values  Get
     * Successful Response
     */
    200: Array<DecimalValueGet | FinancialSimulatorAppServerRoutersValuesRateValueRateValueGet>;
};

export type GetItemsRouteValuesGetResponse = GetItemsRouteValuesGetResponses[keyof GetItemsRouteValuesGetResponses];

export type PostItemRouteValuesPostData = {
    /**
     * Item Post
     */
    body: DecimalValuePost | RateValuePost;
    path?: never;
    query?: never;
    url: '/values/';
};

export type PostItemRouteValuesPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteValuesPostError = PostItemRouteValuesPostErrors[keyof PostItemRouteValuesPostErrors];

export type PostItemRouteValuesPostResponses = {
    /**
     * Response Post Item Route Values  Post
     * Successful Response
     */
    201: DecimalValueGet | FinancialSimulatorAppServerRoutersValuesRateValueRateValueGet;
};

export type PostItemRouteValuesPostResponse = PostItemRouteValuesPostResponses[keyof PostItemRouteValuesPostResponses];

export type DeleteItemRouteValuesItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/values/{item_id}';
};

export type DeleteItemRouteValuesItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteValuesItemIdDeleteError = DeleteItemRouteValuesItemIdDeleteErrors[keyof DeleteItemRouteValuesItemIdDeleteErrors];

export type DeleteItemRouteValuesItemIdDeleteResponses = {
    /**
     * Response Delete Item Route Values  Item Id  Delete
     * Successful Response
     */
    200: DecimalValueGet | FinancialSimulatorAppServerRoutersValuesRateValueRateValueGet;
};

export type DeleteItemRouteValuesItemIdDeleteResponse = DeleteItemRouteValuesItemIdDeleteResponses[keyof DeleteItemRouteValuesItemIdDeleteResponses];

export type GetItemRouteValuesItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/values/{item_id}';
};

export type GetItemRouteValuesItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteValuesItemIdGetError = GetItemRouteValuesItemIdGetErrors[keyof GetItemRouteValuesItemIdGetErrors];

export type GetItemRouteValuesItemIdGetResponses = {
    /**
     * Response Get Item Route Values  Item Id  Get
     * Successful Response
     */
    200: DecimalValueGet | FinancialSimulatorAppServerRoutersValuesRateValueRateValueGet;
};

export type GetItemRouteValuesItemIdGetResponse = GetItemRouteValuesItemIdGetResponses[keyof GetItemRouteValuesItemIdGetResponses];

export type PutItemRouteValuesItemIdPutData = {
    /**
     * Item Post
     */
    body: DecimalValuePost | RateValuePost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/values/{item_id}';
};

export type PutItemRouteValuesItemIdPutErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Response 409 Put Item Route Values  Item Id  Put
     * Database error
     */
    409: HttpDatabaseIntegrityError | HttpChangeTypeError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteValuesItemIdPutError = PutItemRouteValuesItemIdPutErrors[keyof PutItemRouteValuesItemIdPutErrors];

export type PutItemRouteValuesItemIdPutResponses = {
    /**
     * Response Put Item Route Values  Item Id  Put
     * Successful Response
     */
    200: DecimalValueGet | FinancialSimulatorAppServerRoutersValuesRateValueRateValueGet;
};

export type PutItemRouteValuesItemIdPutResponse = PutItemRouteValuesItemIdPutResponses[keyof PutItemRouteValuesItemIdPutResponses];

export type GetItemsRouteSchedulesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/schedules/';
};

export type GetItemsRouteSchedulesGetResponses = {
    /**
     * Response Get Items Route Schedules  Get
     * Successful Response
     */
    200: Array<DailyScheduleGet | DayScheduleGet | YearlyScheduleGet | MonthlyScheduleGet | WeeklyScheduleGet | FromScheduleGet | UntilScheduleGet | RangeScheduleGet | AllScheduleGet | AnyScheduleGet>;
};

export type GetItemsRouteSchedulesGetResponse = GetItemsRouteSchedulesGetResponses[keyof GetItemsRouteSchedulesGetResponses];

export type PostItemRouteSchedulesPostData = {
    /**
     * Item Post
     */
    body: DailySchedulePost | DaySchedulePost | YearlySchedulePost | MonthlySchedulePost | WeeklySchedulePost | FromSchedulePost | UntilSchedulePost | RangeSchedulePost | AllSchedulePost | AnySchedulePost;
    path?: never;
    query?: never;
    url: '/schedules/';
};

export type PostItemRouteSchedulesPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteSchedulesPostError = PostItemRouteSchedulesPostErrors[keyof PostItemRouteSchedulesPostErrors];

export type PostItemRouteSchedulesPostResponses = {
    /**
     * Response Post Item Route Schedules  Post
     * Successful Response
     */
    201: DailyScheduleGet | DayScheduleGet | YearlyScheduleGet | MonthlyScheduleGet | WeeklyScheduleGet | FromScheduleGet | UntilScheduleGet | RangeScheduleGet | AllScheduleGet | AnyScheduleGet;
};

export type PostItemRouteSchedulesPostResponse = PostItemRouteSchedulesPostResponses[keyof PostItemRouteSchedulesPostResponses];

export type DeleteItemRouteSchedulesItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/schedules/{item_id}';
};

export type DeleteItemRouteSchedulesItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteSchedulesItemIdDeleteError = DeleteItemRouteSchedulesItemIdDeleteErrors[keyof DeleteItemRouteSchedulesItemIdDeleteErrors];

export type DeleteItemRouteSchedulesItemIdDeleteResponses = {
    /**
     * Response Delete Item Route Schedules  Item Id  Delete
     * Successful Response
     */
    200: DailyScheduleGet | DayScheduleGet | YearlyScheduleGet | MonthlyScheduleGet | WeeklyScheduleGet | FromScheduleGet | UntilScheduleGet | RangeScheduleGet | AllScheduleGet | AnyScheduleGet;
};

export type DeleteItemRouteSchedulesItemIdDeleteResponse = DeleteItemRouteSchedulesItemIdDeleteResponses[keyof DeleteItemRouteSchedulesItemIdDeleteResponses];

export type GetItemRouteSchedulesItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/schedules/{item_id}';
};

export type GetItemRouteSchedulesItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteSchedulesItemIdGetError = GetItemRouteSchedulesItemIdGetErrors[keyof GetItemRouteSchedulesItemIdGetErrors];

export type GetItemRouteSchedulesItemIdGetResponses = {
    /**
     * Response Get Item Route Schedules  Item Id  Get
     * Successful Response
     */
    200: DailyScheduleGet | DayScheduleGet | YearlyScheduleGet | MonthlyScheduleGet | WeeklyScheduleGet | FromScheduleGet | UntilScheduleGet | RangeScheduleGet | AllScheduleGet | AnyScheduleGet;
};

export type GetItemRouteSchedulesItemIdGetResponse = GetItemRouteSchedulesItemIdGetResponses[keyof GetItemRouteSchedulesItemIdGetResponses];

export type PutItemRouteSchedulesItemIdPutData = {
    /**
     * Item Post
     */
    body: DailySchedulePost | DaySchedulePost | YearlySchedulePost | MonthlySchedulePost | WeeklySchedulePost | FromSchedulePost | UntilSchedulePost | RangeSchedulePost | AllSchedulePost | AnySchedulePost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/schedules/{item_id}';
};

export type PutItemRouteSchedulesItemIdPutErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Response 409 Put Item Route Schedules  Item Id  Put
     * Database error
     */
    409: HttpDatabaseIntegrityError | HttpChangeTypeError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteSchedulesItemIdPutError = PutItemRouteSchedulesItemIdPutErrors[keyof PutItemRouteSchedulesItemIdPutErrors];

export type PutItemRouteSchedulesItemIdPutResponses = {
    /**
     * Response Put Item Route Schedules  Item Id  Put
     * Successful Response
     */
    200: DailyScheduleGet | DayScheduleGet | YearlyScheduleGet | MonthlyScheduleGet | WeeklyScheduleGet | FromScheduleGet | UntilScheduleGet | RangeScheduleGet | AllScheduleGet | AnyScheduleGet;
};

export type PutItemRouteSchedulesItemIdPutResponse = PutItemRouteSchedulesItemIdPutResponses[keyof PutItemRouteSchedulesItemIdPutResponses];

export type GetItemsRouteProvidersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/providers/';
};

export type GetItemsRouteProvidersGetResponses = {
    /**
     * Response Get Items Route Providers  Get
     * Successful Response
     */
    200: Array<AlwaysProviderGet | ScheduledProviderGet | MergeProviderGet | NextProviderGet>;
};

export type GetItemsRouteProvidersGetResponse = GetItemsRouteProvidersGetResponses[keyof GetItemsRouteProvidersGetResponses];

export type PostItemRouteProvidersPostData = {
    /**
     * Item Post
     */
    body: AlwaysProviderPost | ScheduledProviderPost | MergeProviderPost | NextProviderPost;
    path?: never;
    query?: never;
    url: '/providers/';
};

export type PostItemRouteProvidersPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemRouteProvidersPostError = PostItemRouteProvidersPostErrors[keyof PostItemRouteProvidersPostErrors];

export type PostItemRouteProvidersPostResponses = {
    /**
     * Response Post Item Route Providers  Post
     * Successful Response
     */
    201: AlwaysProviderGet | ScheduledProviderGet | MergeProviderGet | NextProviderGet;
};

export type PostItemRouteProvidersPostResponse = PostItemRouteProvidersPostResponses[keyof PostItemRouteProvidersPostResponses];

export type DeleteItemRouteProvidersItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/providers/{item_id}';
};

export type DeleteItemRouteProvidersItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemRouteProvidersItemIdDeleteError = DeleteItemRouteProvidersItemIdDeleteErrors[keyof DeleteItemRouteProvidersItemIdDeleteErrors];

export type DeleteItemRouteProvidersItemIdDeleteResponses = {
    /**
     * Response Delete Item Route Providers  Item Id  Delete
     * Successful Response
     */
    200: AlwaysProviderGet | ScheduledProviderGet | MergeProviderGet | NextProviderGet;
};

export type DeleteItemRouteProvidersItemIdDeleteResponse = DeleteItemRouteProvidersItemIdDeleteResponses[keyof DeleteItemRouteProvidersItemIdDeleteResponses];

export type GetItemRouteProvidersItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/providers/{item_id}';
};

export type GetItemRouteProvidersItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemRouteProvidersItemIdGetError = GetItemRouteProvidersItemIdGetErrors[keyof GetItemRouteProvidersItemIdGetErrors];

export type GetItemRouteProvidersItemIdGetResponses = {
    /**
     * Response Get Item Route Providers  Item Id  Get
     * Successful Response
     */
    200: AlwaysProviderGet | ScheduledProviderGet | MergeProviderGet | NextProviderGet;
};

export type GetItemRouteProvidersItemIdGetResponse = GetItemRouteProvidersItemIdGetResponses[keyof GetItemRouteProvidersItemIdGetResponses];

export type PutItemRouteProvidersItemIdPutData = {
    /**
     * Item Post
     */
    body: AlwaysProviderPost | ScheduledProviderPost | MergeProviderPost | NextProviderPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/providers/{item_id}';
};

export type PutItemRouteProvidersItemIdPutErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Response 409 Put Item Route Providers  Item Id  Put
     * Database error
     */
    409: HttpDatabaseIntegrityError | HttpChangeTypeError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemRouteProvidersItemIdPutError = PutItemRouteProvidersItemIdPutErrors[keyof PutItemRouteProvidersItemIdPutErrors];

export type PutItemRouteProvidersItemIdPutResponses = {
    /**
     * Response Put Item Route Providers  Item Id  Put
     * Successful Response
     */
    200: AlwaysProviderGet | ScheduledProviderGet | MergeProviderGet | NextProviderGet;
};

export type PutItemRouteProvidersItemIdPutResponse = PutItemRouteProvidersItemIdPutResponses[keyof PutItemRouteProvidersItemIdPutResponses];

export type GetDummyDaysGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start
         */
        start?: number;
        /**
         * End
         */
        end?: number;
    };
    url: '/dummy-days/';
};

export type GetDummyDaysGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDummyDaysGetError = GetDummyDaysGetErrors[keyof GetDummyDaysGetErrors];

export type GetDummyDaysGetResponses = {
    /**
     * Successful Response
     */
    200: DummyDayEvent;
};

export type GetDummyDaysGetResponse = GetDummyDaysGetResponses[keyof GetDummyDaysGetResponses];
