// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5174' | (string & {});
};

/**
 * ChangeTypeError
 */
export type ChangeTypeError = {
    /**
     * Type
     */
    type?: 'change-type';
    /**
     * Current Type
     */
    current_type: string;
    /**
     * New Type
     */
    new_type: string;
};

/**
 * CorporationEntityGet
 */
export type CorporationEntityGet = {
    /**
     * Type
     */
    type: 'corporation_entity';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * CorporationEntityPatch
 */
export type CorporationEntityPatch = {
    /**
     * Type
     */
    type: 'corporation_entity';
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CorporationEntityPost
 */
export type CorporationEntityPost = {
    /**
     * Type
     */
    type: 'corporation_entity';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * DatabaseIntegrityError
 */
export type DatabaseIntegrityError = {
    /**
     * Type
     */
    type?: 'database-integrity';
    /**
     * Message
     */
    message: string;
};

/**
 * EntityScenarioGet
 */
export type EntityScenarioGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * EntityScenarioPost
 */
export type EntityScenarioPost = {
    /**
     * Id
     */
    id: string;
};

/**
 * HTTPChangeTypeError
 */
export type HttpChangeTypeError = {
    detail: ChangeTypeError;
};

/**
 * HTTPDatabaseIntegrityError
 */
export type HttpDatabaseIntegrityError = {
    detail: DatabaseIntegrityError;
};

/**
 * HTTPNotFoundError
 */
export type HttpNotFoundError = {
    detail: NotFoundError;
};

/**
 * HTTPRelatedItemNotFoundError
 */
export type HttpRelatedItemNotFoundError = {
    detail: RelatedItemNotFoundError;
};

/**
 * HTTPRelationInvalidError
 */
export type HttpRelationInvalidError = {
    detail: RelationInvalidError;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IndividualEntityGet
 */
export type IndividualEntityGet = {
    /**
     * Type
     */
    type: 'individual_entity';
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * IndividualEntityPatch
 */
export type IndividualEntityPatch = {
    /**
     * Type
     */
    type: 'individual_entity';
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * IndividualEntityPost
 */
export type IndividualEntityPost = {
    /**
     * Type
     */
    type: 'individual_entity';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * NotFoundError
 */
export type NotFoundError = {
    /**
     * Type
     */
    type?: 'not-found';
    /**
     * Id
     */
    id: string;
};

/**
 * RelatedItemNotFoundError
 */
export type RelatedItemNotFoundError = {
    /**
     * Type
     */
    type?: 'related-item-not-found';
    /**
     * Id
     */
    id: string;
};

/**
 * RelationInvalidError
 */
export type RelationInvalidError = {
    /**
     * Type
     */
    type?: 'relation-invalid';
    /**
     * Id
     */
    id: string;
};

/**
 * ScenarioEntityGet
 */
export type ScenarioEntityGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: 'individual_entity' | 'corporation_entity';
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * ScenarioEntityPost
 */
export type ScenarioEntityPost = {
    /**
     * Id
     */
    id: string;
};

/**
 * ScenarioGet
 */
export type ScenarioGet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * ScenarioPatch
 */
export type ScenarioPatch = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ScenarioPost
 */
export type ScenarioPost = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetItemsScenariosGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/scenarios/';
};

export type GetItemsScenariosGetResponses = {
    /**
     * Response Get Items Scenarios  Get
     * Successful Response
     */
    200: Array<ScenarioGet>;
};

export type GetItemsScenariosGetResponse = GetItemsScenariosGetResponses[keyof GetItemsScenariosGetResponses];

export type PostItemScenariosPostData = {
    body: ScenarioPost;
    path?: never;
    query?: never;
    url: '/scenarios/';
};

export type PostItemScenariosPostErrors = {
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemScenariosPostError = PostItemScenariosPostErrors[keyof PostItemScenariosPostErrors];

export type PostItemScenariosPostResponses = {
    /**
     * Successful Response
     */
    201: ScenarioGet;
};

export type PostItemScenariosPostResponse = PostItemScenariosPostResponses[keyof PostItemScenariosPostResponses];

export type DeleteItemScenariosItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}';
};

export type DeleteItemScenariosItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemScenariosItemIdDeleteError = DeleteItemScenariosItemIdDeleteErrors[keyof DeleteItemScenariosItemIdDeleteErrors];

export type DeleteItemScenariosItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGet;
};

export type DeleteItemScenariosItemIdDeleteResponse = DeleteItemScenariosItemIdDeleteResponses[keyof DeleteItemScenariosItemIdDeleteResponses];

export type GetItemScenariosItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}';
};

export type GetItemScenariosItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemScenariosItemIdGetError = GetItemScenariosItemIdGetErrors[keyof GetItemScenariosItemIdGetErrors];

export type GetItemScenariosItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGet;
};

export type GetItemScenariosItemIdGetResponse = GetItemScenariosItemIdGetResponses[keyof GetItemScenariosItemIdGetResponses];

export type PatchItemScenariosItemIdPatchData = {
    body: ScenarioPatch;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}';
};

export type PatchItemScenariosItemIdPatchErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchItemScenariosItemIdPatchError = PatchItemScenariosItemIdPatchErrors[keyof PatchItemScenariosItemIdPatchErrors];

export type PatchItemScenariosItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGet;
};

export type PatchItemScenariosItemIdPatchResponse = PatchItemScenariosItemIdPatchResponses[keyof PatchItemScenariosItemIdPatchResponses];

export type PutItemScenariosItemIdPutData = {
    body: ScenarioPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}';
};

export type PutItemScenariosItemIdPutErrors = {
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemScenariosItemIdPutError = PutItemScenariosItemIdPutErrors[keyof PutItemScenariosItemIdPutErrors];

export type PutItemScenariosItemIdPutResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGet;
};

export type PutItemScenariosItemIdPutResponse = PutItemScenariosItemIdPutResponses[keyof PutItemScenariosItemIdPutResponses];

export type GetRelatedItemsScenariosItemIdEntitiesGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}/entities/';
};

export type GetRelatedItemsScenariosItemIdEntitiesGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRelatedItemsScenariosItemIdEntitiesGetError = GetRelatedItemsScenariosItemIdEntitiesGetErrors[keyof GetRelatedItemsScenariosItemIdEntitiesGetErrors];

export type GetRelatedItemsScenariosItemIdEntitiesGetResponses = {
    /**
     * Response Get Related Items Scenarios  Item Id  Entities  Get
     * Successful Response
     */
    200: Array<ScenarioEntityGet>;
};

export type GetRelatedItemsScenariosItemIdEntitiesGetResponse = GetRelatedItemsScenariosItemIdEntitiesGetResponses[keyof GetRelatedItemsScenariosItemIdEntitiesGetResponses];

export type PostRelatedItemScenariosItemIdEntitiesPostData = {
    body: ScenarioEntityPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}/entities/';
};

export type PostRelatedItemScenariosItemIdEntitiesPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRelatedItemScenariosItemIdEntitiesPostError = PostRelatedItemScenariosItemIdEntitiesPostErrors[keyof PostRelatedItemScenariosItemIdEntitiesPostErrors];

export type PostRelatedItemScenariosItemIdEntitiesPostResponses = {
    /**
     * Successful Response
     */
    201: ScenarioEntityGet;
};

export type PostRelatedItemScenariosItemIdEntitiesPostResponse = PostRelatedItemScenariosItemIdEntitiesPostResponses[keyof PostRelatedItemScenariosItemIdEntitiesPostResponses];

export type DeleteRelatedItemScenariosItemIdEntitiesRelatedItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
        /**
         * Related Item Id
         */
        related_item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}/entities/{related_item_id}';
};

export type DeleteRelatedItemScenariosItemIdEntitiesRelatedItemIdDeleteErrors = {
    /**
     * Response 404 Delete Related Item Scenarios  Item Id  Entities  Related Item Id  Delete
     * Not found
     */
    404: HttpNotFoundError | HttpRelatedItemNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRelatedItemScenariosItemIdEntitiesRelatedItemIdDeleteError = DeleteRelatedItemScenariosItemIdEntitiesRelatedItemIdDeleteErrors[keyof DeleteRelatedItemScenariosItemIdEntitiesRelatedItemIdDeleteErrors];

export type DeleteRelatedItemScenariosItemIdEntitiesRelatedItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ScenarioEntityGet;
};

export type DeleteRelatedItemScenariosItemIdEntitiesRelatedItemIdDeleteResponse = DeleteRelatedItemScenariosItemIdEntitiesRelatedItemIdDeleteResponses[keyof DeleteRelatedItemScenariosItemIdEntitiesRelatedItemIdDeleteResponses];

export type GetRelatedItemScenariosItemIdEntitiesRelatedItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
        /**
         * Related Item Id
         */
        related_item_id: string;
    };
    query?: never;
    url: '/scenarios/{item_id}/entities/{related_item_id}';
};

export type GetRelatedItemScenariosItemIdEntitiesRelatedItemIdGetErrors = {
    /**
     * Response 404 Get Related Item Scenarios  Item Id  Entities  Related Item Id  Get
     * Not found
     */
    404: HttpNotFoundError | HttpRelatedItemNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRelatedItemScenariosItemIdEntitiesRelatedItemIdGetError = GetRelatedItemScenariosItemIdEntitiesRelatedItemIdGetErrors[keyof GetRelatedItemScenariosItemIdEntitiesRelatedItemIdGetErrors];

export type GetRelatedItemScenariosItemIdEntitiesRelatedItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ScenarioEntityGet;
};

export type GetRelatedItemScenariosItemIdEntitiesRelatedItemIdGetResponse = GetRelatedItemScenariosItemIdEntitiesRelatedItemIdGetResponses[keyof GetRelatedItemScenariosItemIdEntitiesRelatedItemIdGetResponses];

export type GetItemsEntitiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/entities/';
};

export type GetItemsEntitiesGetResponses = {
    /**
     * Response Get Items Entities  Get
     * Successful Response
     */
    200: Array<IndividualEntityGet | CorporationEntityGet>;
};

export type GetItemsEntitiesGetResponse = GetItemsEntitiesGetResponses[keyof GetItemsEntitiesGetResponses];

export type PostItemEntitiesPostData = {
    /**
     * Item Post
     */
    body: IndividualEntityPost | CorporationEntityPost;
    path?: never;
    query?: never;
    url: '/entities/';
};

export type PostItemEntitiesPostErrors = {
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostItemEntitiesPostError = PostItemEntitiesPostErrors[keyof PostItemEntitiesPostErrors];

export type PostItemEntitiesPostResponses = {
    /**
     * Response Post Item Entities  Post
     * Successful Response
     */
    201: IndividualEntityGet | CorporationEntityGet;
};

export type PostItemEntitiesPostResponse = PostItemEntitiesPostResponses[keyof PostItemEntitiesPostResponses];

export type DeleteItemEntitiesItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}';
};

export type DeleteItemEntitiesItemIdDeleteErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemEntitiesItemIdDeleteError = DeleteItemEntitiesItemIdDeleteErrors[keyof DeleteItemEntitiesItemIdDeleteErrors];

export type DeleteItemEntitiesItemIdDeleteResponses = {
    /**
     * Response Delete Item Entities  Item Id  Delete
     * Successful Response
     */
    200: IndividualEntityGet | CorporationEntityGet;
};

export type DeleteItemEntitiesItemIdDeleteResponse = DeleteItemEntitiesItemIdDeleteResponses[keyof DeleteItemEntitiesItemIdDeleteResponses];

export type GetItemEntitiesItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}';
};

export type GetItemEntitiesItemIdGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemEntitiesItemIdGetError = GetItemEntitiesItemIdGetErrors[keyof GetItemEntitiesItemIdGetErrors];

export type GetItemEntitiesItemIdGetResponses = {
    /**
     * Response Get Item Entities  Item Id  Get
     * Successful Response
     */
    200: IndividualEntityGet | CorporationEntityGet;
};

export type GetItemEntitiesItemIdGetResponse = GetItemEntitiesItemIdGetResponses[keyof GetItemEntitiesItemIdGetResponses];

export type PatchItemEntitiesItemIdPatchData = {
    /**
     * Item Patch
     */
    body: IndividualEntityPatch | CorporationEntityPatch;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}';
};

export type PatchItemEntitiesItemIdPatchErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Response 409 Patch Item Entities  Item Id  Patch
     * Database error
     */
    409: HttpDatabaseIntegrityError | HttpChangeTypeError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchItemEntitiesItemIdPatchError = PatchItemEntitiesItemIdPatchErrors[keyof PatchItemEntitiesItemIdPatchErrors];

export type PatchItemEntitiesItemIdPatchResponses = {
    /**
     * Response Patch Item Entities  Item Id  Patch
     * Successful Response
     */
    200: IndividualEntityGet | CorporationEntityGet;
};

export type PatchItemEntitiesItemIdPatchResponse = PatchItemEntitiesItemIdPatchResponses[keyof PatchItemEntitiesItemIdPatchResponses];

export type PutItemEntitiesItemIdPutData = {
    /**
     * Item Post
     */
    body: IndividualEntityPost | CorporationEntityPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}';
};

export type PutItemEntitiesItemIdPutErrors = {
    /**
     * Response 409 Put Item Entities  Item Id  Put
     * Database error
     */
    409: HttpDatabaseIntegrityError | HttpChangeTypeError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutItemEntitiesItemIdPutError = PutItemEntitiesItemIdPutErrors[keyof PutItemEntitiesItemIdPutErrors];

export type PutItemEntitiesItemIdPutResponses = {
    /**
     * Response Put Item Entities  Item Id  Put
     * Successful Response
     */
    200: IndividualEntityGet | CorporationEntityGet;
};

export type PutItemEntitiesItemIdPutResponse = PutItemEntitiesItemIdPutResponses[keyof PutItemEntitiesItemIdPutResponses];

export type GetRelatedItemsEntitiesItemIdScenariosGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}/scenarios/';
};

export type GetRelatedItemsEntitiesItemIdScenariosGetErrors = {
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRelatedItemsEntitiesItemIdScenariosGetError = GetRelatedItemsEntitiesItemIdScenariosGetErrors[keyof GetRelatedItemsEntitiesItemIdScenariosGetErrors];

export type GetRelatedItemsEntitiesItemIdScenariosGetResponses = {
    /**
     * Response Get Related Items Entities  Item Id  Scenarios  Get
     * Successful Response
     */
    200: Array<EntityScenarioGet>;
};

export type GetRelatedItemsEntitiesItemIdScenariosGetResponse = GetRelatedItemsEntitiesItemIdScenariosGetResponses[keyof GetRelatedItemsEntitiesItemIdScenariosGetResponses];

export type PostRelatedItemEntitiesItemIdScenariosPostData = {
    body: EntityScenarioPost;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}/scenarios/';
};

export type PostRelatedItemEntitiesItemIdScenariosPostErrors = {
    /**
     * Relation invalid
     */
    400: HttpRelationInvalidError;
    /**
     * Not found
     */
    404: HttpNotFoundError;
    /**
     * Database integrity error
     */
    409: HttpDatabaseIntegrityError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRelatedItemEntitiesItemIdScenariosPostError = PostRelatedItemEntitiesItemIdScenariosPostErrors[keyof PostRelatedItemEntitiesItemIdScenariosPostErrors];

export type PostRelatedItemEntitiesItemIdScenariosPostResponses = {
    /**
     * Successful Response
     */
    201: EntityScenarioGet;
};

export type PostRelatedItemEntitiesItemIdScenariosPostResponse = PostRelatedItemEntitiesItemIdScenariosPostResponses[keyof PostRelatedItemEntitiesItemIdScenariosPostResponses];

export type DeleteRelatedItemEntitiesItemIdScenariosRelatedItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
        /**
         * Related Item Id
         */
        related_item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}/scenarios/{related_item_id}';
};

export type DeleteRelatedItemEntitiesItemIdScenariosRelatedItemIdDeleteErrors = {
    /**
     * Response 404 Delete Related Item Entities  Item Id  Scenarios  Related Item Id  Delete
     * Not found
     */
    404: HttpNotFoundError | HttpRelatedItemNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRelatedItemEntitiesItemIdScenariosRelatedItemIdDeleteError = DeleteRelatedItemEntitiesItemIdScenariosRelatedItemIdDeleteErrors[keyof DeleteRelatedItemEntitiesItemIdScenariosRelatedItemIdDeleteErrors];

export type DeleteRelatedItemEntitiesItemIdScenariosRelatedItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: EntityScenarioGet;
};

export type DeleteRelatedItemEntitiesItemIdScenariosRelatedItemIdDeleteResponse = DeleteRelatedItemEntitiesItemIdScenariosRelatedItemIdDeleteResponses[keyof DeleteRelatedItemEntitiesItemIdScenariosRelatedItemIdDeleteResponses];

export type GetRelatedItemEntitiesItemIdScenariosRelatedItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
        /**
         * Related Item Id
         */
        related_item_id: string;
    };
    query?: never;
    url: '/entities/{item_id}/scenarios/{related_item_id}';
};

export type GetRelatedItemEntitiesItemIdScenariosRelatedItemIdGetErrors = {
    /**
     * Response 404 Get Related Item Entities  Item Id  Scenarios  Related Item Id  Get
     * Not found
     */
    404: HttpNotFoundError | HttpRelatedItemNotFoundError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRelatedItemEntitiesItemIdScenariosRelatedItemIdGetError = GetRelatedItemEntitiesItemIdScenariosRelatedItemIdGetErrors[keyof GetRelatedItemEntitiesItemIdScenariosRelatedItemIdGetErrors];

export type GetRelatedItemEntitiesItemIdScenariosRelatedItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: EntityScenarioGet;
};

export type GetRelatedItemEntitiesItemIdScenariosRelatedItemIdGetResponse = GetRelatedItemEntitiesItemIdScenariosRelatedItemIdGetResponses[keyof GetRelatedItemEntitiesItemIdScenariosRelatedItemIdGetResponses];
